// Context Registry — Additional context for user-facing elements
// Provides drill-down info on hover/click/tap for claims, terms, sections, and points

export interface ContextEntry {
  id: string;
  term: string;
  entity: "BRADESCO" | "BCP" | "CREDICORP" | "AMBIOS" | "SISTEMA";
  category: "iniciativa" | "producto" | "tecnologia" | "metrica" | "termino" | "regulacion";
  shortDef: string;
  fullDef: string;
  comparison?: string;
  estado?: string;
  valor?: string;
  fuentes?: string[];
  confianza?: string;
}

export const CONTEXT_REGISTRY: Record<string, ContextEntry> = {
  // === BRADESCO INICIATIVAS ===
  "BIA": {
    id: "BIA",
    term: "BIA",
    entity: "BRADESCO",
    category: "iniciativa",
    shortDef: "Asistente virtual de Bradesco lanzado en 2016 sobre IBM Watson, hoy 100% GenAI.",
    fullDef: "BIA (Bradesco Inteligência Artificial) es el asistente virtual de Banco Bradesco S.A. Lanzado en 2016 sobre IBM Watson — primera empresa en Brasil en entrenar Watson. Evolucionó a 100% IA generativa en 2025. Procesa voz y texto en app, WhatsApp y web. 24M+ usuarios, 90% retención de demandas digitales, ~40× reducción de costo de atención.",
    comparison: "BCP tiene un asistente virtual en la Banca Móvil BCP, pero no publica métricas de retención equivalentes. La escala de BIA (24M+ usuarios, 90% retención) es superior a cualquier asistente público de BCP documentado.",
    estado: "PRODUCTION_SCALING",
    valor: "24M+ usuarios · 90% retención · ~40× reducción costo atención · 82% resolución primer nivel",
    fuentes: ["S49 (IBM Newsroom)", "S31 (Microsoft)", "S03 (Earnings call 4T25)"],
    confianza: "ALTA (INDEPENDENTLY_CORROBORATED)",
  },
  "BRIDGE": {
    id: "BRIDGE",
    term: "Bridge",
    entity: "BRADESCO",
    category: "iniciativa",
    shortDef: "Plataforma corporativa de IA generativa de Bradesco con multi-LLM, RAG, 7 guardrails.",
    fullDef: "Bridge ('Bradesco Inteligência de Data Generativa') es la plataforma corporativa de GenAI de Banco Bradesco S.A., lanzada en junio 2025. Arquitectura: multi-LLM (múltiples proveedores), RAG (Retrieval-Augmented Generation), 7 Guardrails de seguridad (PII, filtros, compliance), multi-cloud (Azure/AWS/Oracle). 500+ casos de uso en producción, 70 a escala. Conecta datos, modelos, agentes y canales.",
    comparison: "BCP tiene GenIA (herramienta de IA generativa de Credicorp), pero no hay conteo público de casos de uso comparable a los 500 de Bridge. Bradesco comunica mayor granularidad en su plataforma GenAI que BCP.",
    estado: "PRODUCTION",
    valor: "500+ casos de uso · 70 a escala · +35% productividad con Copilot · lead time -43%",
    fuentes: ["S04 (CTO interview)", "S18 (Forbes Brasil)", "S50 (StartSe)", "S51 (DIO)", "S57 (Convergencia Digital)"],
    confianza: "ALTA (INDEPENDENTLY_CORROBORATED)",
  },
  "NEXT": {
    id: "NEXT",
    term: "Next",
    entity: "BRADESCO",
    category: "iniciativa",
    shortDef: "Banco digital de Bradesco para público joven, lanzado 2017, reincorporado al banco matriz 2023-2024.",
    fullDef: "Next fue el primer banco 100% digital de Bradesco, lanzado en junio 2017 para público joven. Alcanzó 10M+ clientes (ene/2022) con Next Shop marketplace (cashback). Reincorporado al banco matriz como segmento de atención (fines 2023-2024) — decisión consciente, NO un fracaso. App sigue activo (Google Play jun/2026).",
    comparison: "BCP no tiene un banco digital separado equivalente a Next. Yape (BCP) cumple parcialmente la función de captura de público digital, pero es una app de pagos, no un banco 100% digital. La reincorporación de Next sugiere que Bradesco consolidó su estrategia digital en el banco matriz.",
    estado: "INTEGRATED (no sunset, no fracaso)",
    valor: "10M+ clientes (2022) · Next Shop marketplace · aprendizaje digital · infraestructura Azure",
    fuentes: ["S44 (O Globo)", "S10 (Google Play)", "S40 (TikTok presence)"],
    confianza: "ALTA (INDEPENDENTLY_CORROBORATED)",
  },
  "BITZ": {
    id: "BITZ",
    term: "Bitz",
    entity: "BRADESCO",
    category: "iniciativa",
    shortDef: "Cartera digital de Bradesco lanzada 2020, cerrada 2023 (absorbida por Digio).",
    fullDef: "Bitz fue una cartera digital de Bradesco lanzada en sep/2020 (cartão virtual Elo, cartão físico débito, QR Code). Meta: 25% del segmento en 3 años. Adquirió fintech 4ward en dic/2020. Formalmente absorbida por Digio en mar/2023 — sunset consciente de consolidación, no fracaso de producto.",
    comparison: "BCP tiene Yape como su cartera/app de pagos — Yape escaló a 20M+ usuarios y se convirtió en superapp, mientras Bitz fue absorbida por Digio. La diferencia de trayectoria (Yape escaló, Bitz fue consolidada) refleja contextos de mercado distintos: Brasil tenía Pix como sistema nacional, mientras Perú necesitaba una solución privada como Yape.",
    estado: "SUNSET (mar/2023, absorbida por Digio)",
    valor: "Experimento de captura de segmento no bancarizado; consolidado en Digio",
    fuentes: ["S41 (Estadão)", "S42 (Mobile Time)", "S43 (Finsiders)"],
    confianza: "ALTA (INDEPENDENTLY_CORROBORATED)",
  },
  "INOVABRA": {
    id: "INOVABRA",
    term: "Inovabra",
    entity: "BRADESCO",
    category: "iniciativa",
    shortDef: "Habitat de co-innovación de Bradesco en São Paulo (22.000 m²), 230 startups, 80 empresas, 8 hubs.",
    fullDef: "Inovabra habitat es un espacio físico de co-innovación de Organização Bradesco, inaugurado en feb/2018 (22.000 m², São Paulo, con WeWork). Conecta startups con producto maduro, corporaciones y hubs. 230 startups, 80 empresas, 8 hubs (2026). Inovabra Ventures: R$400M fondo propio (40% inversiones PE del banco). Startups +55% faturamento (2019). 500 contratos firmados (2021).",
    comparison: "BCP tiene CIX (Centro de Innovación del BCP) con +1 década de operación — es un laboratorio interno, no un habitat abierto como Inovabra. Modelos distintos: Inovabra es co-innovación abierta con startups externas; CIX es exploración→ideación→creación interna. Krealo (Credicorp) es el CVC equivalente a Inovabra Ventures.",
    estado: "MATURE_PRODUCTION",
    valor: "230 startups · R$400M fondo · +55% revenue startups · 500 contratos · 65K visitantes (2019)",
    fuentes: ["S08 (Inovabra official)", "S25 (Finsiders)", "S26 (Mobile Time)", "S27 (CEBDS)"],
    confianza: "ALTA (VERIFIED)",
  },
  "DIGIO": {
    id: "DIGIO",
    term: "Digio",
    entity: "BRADESCO",
    category: "iniciativa",
    shortDef: "Banco digital subsidiario de Bradesco (100% desde 2021-2022), infraestructura AWS separada.",
    fullDef: "Banco Digio S.A. es un banco digital subsidiario de Banco Bradesco S.A. Inicialmente JV con Banco do Brasil (50/50). Bradesco compró el 49,99% restante por R$625M en 2021-2022. Infraestructura en AWS (separada de Next/Azure). Management declaró intención de mantenerlo como unidad independiente. Absorbió clientes de Bitz en 2023.",
    comparison: "BCP no tiene un banco digital subsidiario equivalente a Digio. La estrategia de Bradesco de mantener dos infraestructuras cloud separadas (Next/Azure + Digio/AWS) no tiene equivalente público en BCP.",
    estado: "PRODUCTION",
    valor: "R$625M adquisición · infraestructura AWS independiente · absorbió clientes Bitz",
    fuentes: ["S06 (multicloud announcement)", "S01 (20-F)"],
    confianza: "ALTA (INDEPENDENTLY_CORROBORATED)",
  },
  "DREX": {
    id: "DREX",
    term: "Drex",
    entity: "BRADESCO",
    category: "tecnologia",
    shortDef: "Piloto de real digital (CBDC) del Banco Central do Brasil. Bradesco participa. BC pivotó sin blockchain 2026.",
    fullDef: "Drex es el real digital del Banco Central do Brasil (CBDC). Bradesco participa en el piloto probando préstamos con garantías tokenizadas, debêntures digitales y crédito colateralizado en CDB mediante smart contracts. En ago/2025, el BC anunció que Drex abandonará blockchain/DLT en su fase de corto plazo, lanzando versión simplificada sin tokenización para 2S2026.",
    comparison: "BCP/Yape participa en el piloto CBDC del BCRP (Perú) con 107K usuarios y 41K tx/diarias. Ambos bancos experimentan con CBDC pero en contextos regulatorios distintos: Drex (Brasil, BC pivotó sin blockchain) vs BCRP CBDC (Perú, piloto activo con Yape).",
    estado: "EXPERIMENT (BC pivotó Drex sin blockchain para fase corta 2026)",
    valor: "Aprendizaje de tokenización y smart contracts; horizonte incierto tras pivote del BC",
    fuentes: ["S61 (BCB)"],
    confianza: "ALTA (INDEPENDENTLY_CORROBORATED)",
  },

  // === BCP INICIATIVAS ===
  "YAPE": {
    id: "YAPE",
    term: "Yape",
    entity: "BCP",
    category: "iniciativa",
    shortDef: "App de pagos/superapp de BCP Perú. 20M+ usuarios, 15M+ MAU, ~75% población Perú.",
    fullDef: "Yape es la app de pagos móviles de Banco de Crédito del Perú (BCP), lanzada en feb/2017. Evolucionó de billetera digital a superapp. Permite pagos QR, transferencias P2P, recargas, pago de servicios. No requiere cuenta bancaria BCP. 20M+ usuarios totales, 15M+ MAU, ~75% de la población de Perú, 23M+ usuarios diarios. Tercera app más usada en Perú (McKinsey). Breakeven alcanzado con 12.3M+ usuarios. 541K personas recibieron primer crédito via Yape (2024).",
    comparison: "Bradesco tiene Pix (sistema nacional de pagos instantáneos) que procesa 68.7B transacciones/año — pero Pix es infraestructura nacional obligatoria, no una app de un banco. Yape es un producto de BCP que cumple una función similar a Pix pero en un mercado sin sistema nacional equivalente. Next (Bradesco) tenía 10M+ clientes antes de reincorporación — Yape (20M+) tiene mayor escala.",
    estado: "PRODUCTION_SCALING",
    valor: "20M+ users · 15M+ MAU · ~75% pop. Perú · 23M+ daily · 541K primer crédito · 65% ingresos disrupción grupo",
    fuentes: ["S47 (Credicorp)", "S54 (Nuvei)", "S55 (McKinsey)", "S12 (Credicorp IR)"],
    confianza: "ALTA (INDEPENDENTLY_CORROBORATED)",
  },
  "CRIPTOCOCOS": {
    id: "CRIPTOCOCOS",
    term: "CriptoCocos",
    entity: "BCP",
    category: "iniciativa",
    shortDef: "Primera plataforma bancaria de criptoactivos del Perú. Bitcoin + USDC. Sandbox SBS. ~3.000 clientes.",
    fullDef: "CriptoCocos es la primera plataforma bancaria de criptoactivos del Perú, lanzada por BCP en oct/2025. Permite comprar/vender Bitcoin y USDC con custodia institucional de BitGo. Autorizada por SBS dentro del sandbox regulatorio. Limitada a ~3.000 clientes en fase piloto. BCP es el único banco peruano con un proyecto de esta naturaleza.",
    comparison: "Bradesco no tiene un producto de cripto retail equivalente a CriptoCocos. Bradesco experimenta con Drex (CBDC) y tiene partnership con Parfin para stablecoins cross-border, pero no ofrece compra/venta de Bitcoin/USDC a clientes retail como BCP. BCP está ADELANTE de Bradesco en cripto retail regulado.",
    estado: "PILOT (sandbox SBS, ~3.000 clientes)",
    valor: "Posicionamiento pionero cripto bancario LatAm · aprendizaje regulatorio · acceso regulado a cripto",
    fuentes: ["S62 (BitGo)", "S63 (BusinessWire)"],
    confianza: "ALTA (INDEPENDENTLY_CORROBORATED)",
  },
  "CIX": {
    id: "CIX",
    term: "CIX",
    entity: "BCP",
    category: "iniciativa",
    shortDef: "Centro de Innovación del BCP, +1 década activo. Proceso: Exploración→Ideación→Creación.",
    fullDef: "CIX (Centro de Innovación del BCP) es un laboratorio interno de BCP con más de una década de operación. Sigue el proceso: Exploración → Ideación → Creación. Activo en 2025 (#InnovationDay2025). No es un proyecto histórico de GitHub — es un centro de innovación en operación continua.",
    comparison: "Bradesco tiene Inovabra habitat (espacio físico 22.000 m², 230 startups, co-innovación abierta con WeWork). CIX es un laboratorio interno (no habitat abierto). Modelos distintos: Inovabra es co-innovación con startups externas; CIX es exploración interna. Ambos son MATURE/PRODUCTION.",
    estado: "MATURE_PRODUCTION (+1 década activo)",
    valor: "Innovación interna continua · cultura de aprendizaje · #InnovationDay2025",
    fuentes: ["S36 (Instagram @cix.bcp)", "S37 (Viabcp)"],
    confianza: "ALTA (INDEPENDENTLY_CORROBORATED)",
  },
  "GENIA": {
    id: "GENIA",
    term: "GenIA",
    entity: "BCP",
    category: "iniciativa",
    shortDef: "Herramienta de IA generativa de Credicorp/BCP. Pionero en Perú en IA gen para software.",
    fullDef: "GenIA es la herramienta de IA generativa de Credicorp/BCP. BCP es pionero en Perú en uso de IA generativa para desarrollar software (Forbes Perú, dic/2024), con marco de 10+ prácticas (revisiones código, pruebas automatizadas). También implementa GenAI en voz para atención de clientes (ene/2025). AI Automation Specialist en Credicorp Capital.",
    comparison: "Bradesco tiene Bridge (500+ casos de uso, multi-LLM, RAG, 7 guardrails) — plataforma más documentada públicamente. GenIA de BCP no tiene conteo público de casos de uso comparable. Bradesco comunica mayor granularidad, pero BCP fue pionero en Perú en IA gen para software.",
    estado: "PRODUCTION",
    valor: "Pionero Perú IA gen software · marco 10+ prácticas · GenAI voice atención clientes",
    fuentes: ["S28 (Forbes Perú)", "S30 (Credicorp GenIA)", "S33 (Credicorp 4Q25)"],
    confianza: "ALTA (INDEPENDENTLY_CORROBORATED)",
  },
  "BCP_XPLORE": {
    id: "BCP_XPLORE",
    term: "BCP Xplore",
    entity: "BCP",
    category: "iniciativa",
    shortDef: "Unidad de Open Banking/APIs de BCP. Recaudación, pagos automáticos, financiamiento flexible.",
    fullDef: "BCP Xplore es la unidad de Open Banking/APIs de Banco de Crédito del Perú. Ofrece servicios de recaudación, pagos automáticos y financiamiento flexible exclusivos para clientes del programa. Es la respuesta de BCP al ecosistema Open Banking peruano.",
    comparison: "Bradesco es participante obligatorio de Open Finance Brasil (BACEN, desde 2021) — marco más maduro que el peruano. BCP Xplore es una iniciativa propia de Open Banking, mientras Bradesco cumple con el marco obligatorio BACEN. Diferencia regulatoria: Brasil tiene Open Finance obligatorio; Perú está en desarrollo.",
    estado: "PRODUCTION",
    valor: "APIs de recaudación · pagos automáticos · financiamiento flexible · ecosistema fintech",
    fuentes: ["S15 (BCP Xplore official)"],
    confianza: "ALTA (VERIFIED)",
  },

  // === CREDICORP INICIATIVAS ===
  "KREALO": {
    id: "KREALO",
    term: "Krealo",
    entity: "CREDICORP",
    category: "iniciativa",
    shortDef: "Fondo de venture corporativo de Credicorp. 16 startups en portfolio. Expansión a Ecuador.",
    fullDef: "Krealo es el fondo de Corporate Venture Capital (CVC) de Credicorp Ltd. Enfoque 'hands-on' tipo VC. Portfolio regional de 16 startups, foco en fintech AI solutions. 8 transacciones en 2025. Expansión a Ecuador con inversión en Jelou (mar/2026). Tenpo autorizado como banco en Chile (ene/2026).",
    comparison: "Bradesco tiene Inovabra Ventures (R$400M fondo propio, 40% de inversiones PE del banco) — equivalente funcional a Krealo. Ambos son CVC con enfoque fintech. Krealo tiene 16 startups en portfolio; Inovabra Ventures no publica conteo equivalente pero tiene R$400M de capital.",
    estado: "PRODUCTION",
    valor: "16 startups · 8 transacciones 2025 · expansión Ecuador · Tenpo primer neobanco Chile",
    fuentes: ["S46 (Krealo)", "S56 (Krealo insights)"],
    confianza: "ALTA (INDEPENDENTLY_CORROBORATED)",
  },
  "TENPO": {
    id: "TENPO",
    term: "Tenpo",
    entity: "CREDICORP",
    category: "iniciativa",
    shortDef: "Fintech/neobanco de Credicorp en Chile. Primer neobanco autorizado en Chile (ene/2026). 754K clientes.",
    fullDef: "Tenpo es una fintech impulsada por Krealo (Credicorp) en Chile. En enero de 2026 se convirtió en el primer neobanco autorizado en Chile. Cuenta digital $0, tarjeta Mastercard. 754K clientes (fin 2024). Inicio de operaciones bancarias previsto para 1S2026.",
    comparison: "Bradesco no tiene un neobanco internacional equivalente a Tenpo. Next (Bradesco) era un banco digital doméstico (Brasil) que fue reincorporado. Tenpo representa la expansión internacional de Credicorp fuera de Perú — algo que Bradesco no ha hecho públicamente con marcas digitales.",
    estado: "PRODUCTION (primer neobanco Chile, ene/2026)",
    valor: "754K clientes · primer neobanco Chile · expansión internacional Credicorp",
    fuentes: ["S56 (Krealo)", "Credicorp Annual Report 2024"],
    confianza: "ALTA (INDEPENDENTLY_CORROBORATED)",
  },
  "MIBANCO": {
    id: "MIBANCO",
    term: "Mibanco",
    entity: "CREDICORP",
    category: "iniciativa",
    shortDef: "Líder de microfinanzas en Perú (Credicorp). 4.1M personas incluidas, 56% mujeres.",
    fullDef: "Mibanco es el líder de microfinanzas en Perú, subsidiaria de Credicorp. Incluyó a 4.1M personas en el sistema financiero. 64K clientes (56% mujeres). S/108.5M desembolsados a 63.6K clientes. Modelo de agencia compartida con BCP (ej: Órganos).",
    comparison: "Bradesco NO tiene un equivalente de microfinanzas. Mibanco es una ventaja estructural de Credicorp en inclusión financiera que Bradesco no replica. Esta es una dimensión donde BCP/Credicorp es estructuralmente más fuerte.",
    estado: "PRODUCTION",
    valor: "4.1M personas incluidas · 64K clientes (56% mujeres) · S/108.5M desembolsados · líder microfinanzas Perú",
    fuentes: ["S81 (Grupo Credicorp)"],
    confianza: "ALTA (VERIFIED)",
  },

  // === TECNOLOGÍAS ===
  "PIX": {
    id: "PIX",
    term: "Pix",
    entity: "BRADESCO",
    category: "tecnologia",
    shortDef: "Sistema nacional de pagos instantáneos de Brasil (BACEN, 2020). 68.7B transacciones en 2024.",
    fullDef: "Pix es el sistema nacional de pagos instantáneos del Banco Central do Brasil (BACEN), lanzado en noviembre 2020. Bradesco es institución participante. 68.7B transacciones en 2024 (+52% YoY). USD 6.7T volumen proyectado 2025. 8B transacciones mensuales.",
    comparison: "Perú no tiene un sistema nacional equivalente a Pix. Yape (BCP) cumple parcialmente esa función pero es una app de un banco, no un sistema nacional obligatorio. La madurez de Pix (Brasil) vs la ausencia de equivalente nacional (Perú) explica parte de la diferencia en casos de uso digital observable (hipótesis H4).",
    estado: "MATURE (sistema nacional obligatorio desde 2020)",
    valor: "68.7B tx/año (2024) · USD 6.7T volumen proyectado 2025 · 8B tx mensuales",
    fuentes: ["S82 (BCB)"],
    confianza: "ALTA (VERIFIED)",
  },
  "OPEN_FINANCE": {
    id: "OPEN_FINANCE",
    term: "Open Finance",
    entity: "BRADESCO",
    category: "regulacion",
    shortDef: "Marco regulatorio obligatorio de Open Finance en Brasil (BACEN, desde 2021). Bradesco participa.",
    fullDef: "Open Finance Brasil es un marco regulatorio obligatorio del Banco Central do Brasil (BACEN) desde 2021. Bradesco es institución participante activa. Permite a clientes compartir datos financieros entre instituciones mediante APIs estandarizadas.",
    comparison: "Perú no tiene un marco de Open Finance obligatorio equivalente al brasileño. BCP Xplore es una iniciativa propia de Open Banking, no un cumplimiento regulatorio. Diferencia regulatoria: Brasil obligatorio desde 2021; Perú en desarrollo.",
    estado: "MATURE (obligatorio BACEN desde 2021)",
    valor: "APIs estandarizadas · interoperabilidad · portabilidad de datos · ecosistema fintech",
    fuentes: ["S38 (Bradesco Open Finance page)"],
    confianza: "ALTA (VERIFIED)",
  },
  "FICO": {
    id: "FICO",
    term: "FICO Platform",
    entity: "AMBIOS",
    category: "tecnologia",
    shortDef: "Plataforma de decisioning/fraude usada por AMBOS bancos (Bradesco y BCP).",
    fullDef: "FICO Platform es una solución de decisioning y detección de fraude usada por ambos bancos. Bradesco: SAFER/FICO procesa 25M transacciones Pix/día, -89% revisiones manuales, -25% rechazos. BCP: usa FICO para maximizar rentabilidad, reducir carga operativa, onboarding nuevos segmentos.",
    comparison: "AMBOS bancos (Bradesco y BCP) usan FICO Platform — mismo vendor para fraud/decisioning. Bradesco documenta outcomes más específicos (25M tx/día, -89% revisiones). BCP también implementa Lynx Tech AI (-30% fraude documentado). La adopción de FICO es una similitud tecnológica clave entre ambos bancos.",
    estado: "PRODUCTION (ambos bancos)",
    valor: "Bradesco: 25M tx/día, -89% revisiones · BCP: rentabilidad, onboarding segmentos",
    fuentes: ["S32 (FICO Bradesco)", "S72 (FICO SAFER detail)", "S84 (FICO BCP)"],
    confianza: "ALTA (STRONGLY_SUPPORTED)",
  },

  // === TECNOLOGÍAS EMERGENTES ===
  "QUANTUM_SAFE": {
    id: "QUANTUM_SAFE",
    term: "Quantum-safe encryption",
    entity: "BRADESCO",
    category: "tecnologia",
    shortDef: "Piloto de Bradesco con IBM Research para encriptación resistente a computación cuántica (2024).",
    fullDef: "Bradesco realizó un piloto de encriptación privacy-preserving resistente a computación cuántica con datos financieros reales, en colaboración con IBM Research (2024). También contrató IBM Quantum Safe Explorer para mapear vulnerabiliedades criptográficas y se unió a la IBM Quantum Network. Partnership con USP (INOVA) para R&D en quantum computing, IA y cybersecurity.",
    comparison: "BCP no tiene evidencia pública de pilotos de computación cuántica o encriptación post-cuántica. Bradesco lidera en esta dimensión con IBM Research + USP. BCP no publica equivalente.",
    estado: "EXPERIMENT_PILOT (criptografía post-cuántica en mapeo/piloto; computación cuántica en exploración)",
    valor: "Preparación para amenaza cuántica · mapeo de vulnerabilidades · R&D con IBM+USP",
    fuentes: ["S21 (IBM Research)", "S77 (TI Inside USP)", "S78 (Security Leaders)"],
    confianza: "ALTA (STRONGLY_SUPPORTED)",
  },
  "AGENTIC_AI": {
    id: "AGENTIC_AI",
    term: "Agentic AI",
    entity: "BRADESCO",
    category: "tecnologia",
    shortDef: "Arquitecturas multi-agente mencionadas dentro de Bridge. Sin escala específica divulgada.",
    fullDef: "Agentic AI se refiere a sistemas de IA que pueden tomar acciones autónomas. Bradesco menciona servicios reutilizables multi-agente dentro de la plataforma Bridge. La CTO Cíntia Scovine mencionó agentes en feb/2026. No se discloseó escala específica de producción.",
    comparison: "BCP no publica evidencia de arquitecturas agentic AI o multi-agente. Bradesco menciona agentic AI dentro de Bridge pero sin métricas específicas. Ambos bancos están en fase exploratoria en esta dimensión.",
    estado: "EXPERIMENT_PILOT (mencionado en Bridge, sin escala específica)",
    valor: "Exploración de autonomía de IA · agentes reutilizables · potencial de automatización avanzada",
    fuentes: ["S04 (CTO interview)"],
    confianza: "MEDIA (PARTIAL)",
  },
  "MULTIMODAL_AI": {
    id: "MULTIMODAL_AI",
    term: "Multimodal AI",
    entity: "BRADESCO",
    category: "tecnologia",
    shortDef: "Bain confirma Bradesco pilota IA multimodal: voz, imagen, texto (verano 2025).",
    fullDef: "Bain & Company confirma que Bradesco pilota una solución agentic con IA multimodal que incluye solicitudes de voz, interpretación de imágenes y procesamiento de texto. Pilot en verano 2025.",
    comparison: "BCP no publica evidencia de IA multimodal específica. Bradesco lidera con pilot confirmado por Bain (Tier C). BCP tiene GenIA (IA generativa voice para atención) pero no multimodal integral.",
    estado: "EXPERIMENT_PILOT (piloto verano 2025, confirmado por Bain)",
    valor: "Procesamiento simultáneo voz+imagen+texto · experiencias de cliente más ricas",
    fuentes: ["S52 (Bain & Company)"],
    confianza: "ALTA (STRONGLY_SUPPORTED)",
  },
  "TERRAFORM": {
    id: "TERRAFORM",
    term: "Terraform",
    entity: "BRADESCO",
    category: "tecnologia",
    shortDef: "Bradesco aceleró provisionamiento de infraestructura de 80 días a 5 usando Terraform (abr/2026).",
    fullDef: "Bradesco implementó Terraform (HashiCorp) como backbone de su estrategia de platform engineering, transformando el provisionamiento de infraestructura de 80 días a 5 días (94% reducción). Caso de estudio HashiCorp (abr/2026).",
    comparison: "BCP no publica métricas equivalentes de platform engineering o Terraform. Bradesco documenta una transformación de DevOps más específica que BCP. BCP invierte $650M en IT modernización pero sin detalle de Terraform.",
    estado: "PRODUCTION (platform engineering transformation)",
    valor: "80 días → 5 días (94% reducción) · platform engineering · self-service infra",
    fuentes: ["S53 (HashiCorp)"],
    confianza: "ALTA (STRONGLY_SUPPORTED)",
  },
  "COPILOT": {
    id: "COPILOT",
    term: "Microsoft 365 Copilot + GitHub Copilot",
    entity: "BRADESCO",
    category: "tecnologia",
    shortDef: "Bradesco usa Copilot para productividad de desarrolladores: +35% productividad (nov/2025).",
    fullDef: "Bradesco implementó Microsoft 365 Copilot + GitHub Copilot para productividad de desarrolladores. Las unidades de negocio pueden crear y gestionar agentes de IA. Aumento de hasta 35% en productividad (Microsoft case study, nov/2025).",
    comparison: "BCP es pionero en Perú en IA generativa para desarrollar software (Forbes Perú, dic/2024) con marco de 10+ prácticas, pero no publica métricas de productividad equivalentes al +35% de Bradesco. Ambos bancos usan IA en desarrollo de software.",
    estado: "PRODUCTION (+35% productividad documentada)",
    valor: "+35% productividad desarrolladores · creación de agentes de IA · self-service",
    fuentes: ["S31 (Microsoft Azure AI case study)"],
    confianza: "ALTA (STRONGLY_SUPPORTED)",
  },

  // === MÉTRICAS Y TÉRMINOS ===
  "ROAE": {
    id: "ROAE",
    term: "ROAE",
    entity: "SISTEMA",
    category: "metrica",
    shortDef: "Retorno sobre patrimonio promedio (Return on Average Equity). Medida de rentabilidad.",
    fullDef: "ROAE (Return on Average Equity) mide la rentabilidad de un banco sobre su patrimonio promedio. Es una métrica adimensional (porcentaje) comparable entre bancos si los períodos están alineados. Bradesco ROAE 4T25: 15.2% (primera vez > costo de capital). BCP ROAE FY2025: 24.7%. Bradesco 2T26: 16.2% (10º trimestre consecutivo de mejora).",
    comparison: "BCP ROAE 24.7% (FY2025) es significativamente superior a Bradesco ROAE 16.2% (2T26). La diferencia puede reflejar ciclo de crédito y estructura de mercado, no solo capacidad operativa. BCP tiene costo de riesgo 1.28% (cayó de 2.13%) — impulsor clave del ROAE.",
    estado: "COMPARABLE (dimensión adimensional)",
    valor: "Bradesco 16.2% (2T26, 10º trimestre mejora) · BCP 24.7% (FY2025)",
    fuentes: ["S02 (6-K 4T25)", "S64 (Seu Dinheiro 2T26)", "S13 (SBS BCP)"],
    confianza: "ALTA (VERIFIED)",
  },
  "EFICIENCIA": {
    id: "EFICIENCIA",
    term: "Índice de eficiencia",
    entity: "SISTEMA",
    category: "metrica",
    shortDef: "Gastos administrativos / margen financiero. Bradesco: 50% (meta 40% en 2028).",
    fullDef: "El índice de eficiencia mide los gastos administrativos como porcentaje del margen financiero (convención brasileña). Un índice menor es mejor. Bradesco cerró 2025 en 50%, con meta declarada de 40% para 2028. BCP no divulga el índice de eficiencia con la misma definición.",
    comparison: "Bradesco 50% (meta 40% 2028) — BCP no divulga con misma definición. Comparación PARTIAL: direccionalmente comparable pero no al basis point sin reconciliación de definición.",
    estado: "PARTIAL (definiciones varían por jurisdicción)",
    valor: "Bradesco 50% → meta 40% (2028) · 10pp de mejora estructural en 3 años",
    fuentes: ["S03 (Earnings call 4T25)"],
    confianza: "ALTA (STRONGLY_SUPPORTED)",
  },
  "OPEN_FINANCE_BRASIL": {
    id: "OPEN_FINANCE_BRASIL",
    term: "Open Finance Brasil",
    entity: "BRADESCO",
    category: "regulacion",
    shortDef: "Marco regulatorio obligatorio de Open Finance en Brasil (BACEN, desde 2021). Bradesco participa.",
    fullDef: "Open Finance Brasil es un marco regulatorio obligatorio del Banco Central do Brasil (BACEN) desde 2021. Requiere que instituciones financieras expongan APIs estandarizadas para que clientes puedan compartir datos financieros entre instituciones. Bradesco es institución participante activa.",
    comparison: "Perú no tiene marco de Open Finance obligatorio equivalente. BCP Xplore es iniciativa propia de Open Banking, no cumplimiento regulatorio. Diferencia regulatoria clave (hipótesis H4): Brasil obligatorio desde 2021; Perú en desarrollo.",
    estado: "MATURE (obligatorio BACEN desde 2021)",
    valor: "APIs estandarizadas · interoperabilidad · portabilidad datos · ecosistema fintech",
    fuentes: ["S38 (Bradesco Open Finance page)", "S61 (BCB)"],
    confianza: "ALTA (VERIFIED)",
  },
  "SUNAT": {
    id: "SUNAT",
    term: "SUNAT",
    entity: "CREDICORP",
    category: "regulacion",
    shortDef: "Disputa fiscal de Credicorp con SUNAT: S/1.568B (~23% utilidad anual), pago bajo protesta.",
    fullDef: "La Superintendencia Nacional de Aduanas y de Administración Tributaria (SUNAT) del Perú tiene una disputa activa con Credicorp por S/1.568 mil millones (~23% de la utilidad neta anual). Credicorp pagó bajo protesta y el litigio está activo. Esto representa un riesgo regulatorio material cuantificado.",
    comparison: "Bradesco tiene litigios fiscales con CVM (BEM DTVM, UEG Araucaria) y contingencias fiscales de R$38.29B (riesgo posible), pero la mayoría son contingencia fuera de balance. El perfil de riesgo es distinto: Credicorp más líquido/político (pago bajo protesta), Bradesco más contingencia fiscal.",
    estado: "ACTIVO (litigio en curso, pago bajo protesta)",
    valor: "S/1.568B en disputa (~23% utilidad anual) — riesgo material cuantificado",
    fuentes: ["S67 (Credicorp IR)"],
    confianza: "ALTA (VERIFIED)",
  },
  "CVM": {
    id: "CVM",
    term: "CVM",
    entity: "BRADESCO",
    category: "regulacion",
    shortDef: "Comisión de Valores Mobiliarios de Brasil. Proceso sancionador vs BEM DTVM (may/2025).",
    fullDef: "La Comisión de Valores Mobiliarios (CVM) de Brasil abrió un proceso sancionador contra BEM DTVM (administradora de Bradesco) en mayo 2025 por supuestas irregularidades en la administración de inversiones de una termoeléctrica (UEG Araucaria). Otros procesos por falta de deber de diligencia y multa a Bradesco Corretora. Monto no cuantificado.",
    comparison: "Credicorp tiene disputa SUNAT de S/1.568B (23% utilidad, cuantificada). Bradesco tiene contingencias fiscales R$38.29B (riesgo posible, no provisionado) + CVM proceso (monto no cuantificado). Perfiles de riesgo distintos: Credicorp más cuantificado, Bradesco más voluminoso pero contingente.",
    estado: "ACTIVO (proceso sancionador en curso)",
    valor: "Monto no cuantificado · R$38.29B contingencias fiscales (riesgo posible)",
    fuentes: ["S68 (CVM)"],
    confianza: "ALTA (VERIFIED)",
  },
  "MULTICLOUD": {
    id: "MULTICLOUD",
    term: "Multicloud",
    entity: "BRADESCO",
    category: "tecnologia",
    shortDef: "Estrategia multicloud de Bradesco: Azure (Next), AWS (Digio), Oracle (Seguros), mixed (parent). 35% cloud.",
    fullDef: "Bradesco declaró estrategia multicloud en feb/2024: sistemas nuevos nacen cloud-first (100% nube), pero el legado de 80 años no se migra salvo necesidad efectiva. 35% de cargas en nube (feb/2024). Distribución: Next sobre Azure; Digio sobre AWS; Bradesco Seguros sobre Oracle; banco matriz usa Azure+IBM+AWS. No hay fecha objetivo de 100% cloud.",
    comparison: "BCP no publica una estrategia multicloud equivalente con detalle de proveedores por subsidiaria. Bradesco documenta una estrategia multi-cloud deliberada (3+ proveedores) que BCP no publica con misma granularidad.",
    estado: "SCALING (35% workloads cloud, cloud-first para nuevos)",
    valor: "Cloud-first nuevos sistemas · legado migrado solo por necesidad · 3+ proveedores",
    fuentes: ["S06 (multicloud announcement)", "S07 (Teradata case study)"],
    confianza: "ALTA (STRONGLY_SUPPORTED)",
  },
  "BBI": {
    id: "BBI",
    term: "Bradesco BBI",
    entity: "BRADESCO",
    category: "iniciativa",
    shortDef: "Banco Bradesco BBI — brazo de banca de inversión de Bradesco.",
    fullDef: "Banco Bradesco BBI es el brazo de banca de inversión de Organização Bradesco. Proporciona servicios de advisory en M&A, estructuración de deuda y emisiones de capital, tanto doméstica como internacionalmente, así como estructurado y project finance.",
    comparison: "BCP/Credicorp tiene Credicorp Capital como su brazo de banca de inversión y wealth management. Ambos grupos tienen brazos de banca de inversión dedicados — estructuralmente comparables.",
    estado: "PRODUCTION",
    valor: "Advisory M&A · estructuración deuda · emisiones capital · project finance",
    fuentes: ["bradescobbi.com.br"],
    confianza: "MEDIA (STRONGLY_SUPPORTED)",
  },
  "AGORA": {
    id: "AGORA",
    term: "Ágora",
    entity: "BRADESCO",
    category: "iniciativa",
    shortDef: "Ágora Corretora — brazo de corretaje y wealth management de Bradesco (adquirida 2008).",
    fullDef: "Ágora Corretora de Câmbio e Títulos S.A. es la brazo de corretaje y wealth management de Organização Bradesco, adquirida en 2008. Ofrece corretaje de valores, fondos de inversión y gestión de patrimonios para clientes affluent y private.",
    comparison: "BCP tiene BCP Wealth / Credicorp Capital para wealth management. Ambos grupos tienen brazos de wealth/corretaje — estructuralmente comparables.",
    estado: "PRODUCTION",
    valor: "Corretaje · wealth management · fondos · gestión patrimonios",
    fuentes: ["S01 (20-F)"],
    confianza: "ALTA (VERIFIED)",
  },
  "SEGUROS": {
    id: "SEGUROS",
    term: "Bradesco Seguros",
    entity: "BRADESCO",
    category: "iniciativa",
    shortDef: "Brazo de seguros de Bradesco. ROAE 21.9% — más rentable que el banco. Incluye Odontoprev (2026).",
    fullDef: "Bradesco Seguros S.A. es el brazo de seguros de Organização Bradesco. Incluye Bradesco Vida e Previdência, Bradesco Saúde, Bradesco Capitalização, y la consolidación de Bradesco Gestão de Saúde + Odontoprev (feb/2026). ROAE 21.9% en 2025 — más rentable que el brazo bancario (15.2%). Utilidad neta R$10.1B. Activos R$507.8B.",
    comparison: "Credicorp tiene Grupo Pacífico (seguros) y Prima AFP (pensiones) como equivalentes funcionales. Ambos grupos son multi-negocio (banca+seguros+pensiones). Bradesco Seguros ROAE 21.9% supera al brazo bancario — dinámica similar a Credicorp donde seguros contribuyen significativamente.",
    estado: "PRODUCTION (consolidando Odontoprev 2026)",
    valor: "ROAE 21.9% · R$10.1B utilidad · R$507.8B activos · +comprehensive health insurance Brasil",
    fuentes: ["S01 (20-F)", "S60 (Odontoprev consolidation)"],
    confianza: "ALTA (VERIFIED)",
  },
  "STABLECOIN": {
    id: "STABLECOIN",
    term: "Stablecoin (Parfin)",
    entity: "BRADESCO",
    category: "tecnologia",
    shortDef: "Partnership Bradesco-Parfin para stablecoins en pagos transfronterizos (ene/2025). R$10B capital para custodia.",
    fullDef: "Bradesco anunció partnership estratégico con Parfin (ene/2025) para explorar uso de stablecoins en pagos transfronterizos y comercio internacional. Ejecutivo declaró 'no turning back'. En jul/2026, Bradesco aprobó aumento de capital de R$10B para blockchain, stablecoin y custodia de activos digitales.",
    comparison: "BCP tiene CriptoCocos (Bitcoin+USDC, PILOT sandbox SBS) y Blockchain Gifts (token GIFT Polygon). BCP está ADELANTE en cripto retail regulado (CriptoCocos), mientras Bradesco avanza en stablecoins institucionales (Parfin). Dimensiones distintas del ecosistema cripto.",
    estado: "PILOT (Parfin partnership ene/2025, R$10B capital jul/2026)",
    valor: "Pagos transfronterizos · comercio internacional · R$10B para custodia digital",
    fuentes: ["S22 (Parfin)", "S23 (Valor International)", "S24 (Crypto Briefing)"],
    confianza: "ALTA (INDEPENDENTLY_CORROBORATED)",
  },
  "ESG": {
    id: "ESG",
    term: "ESG",
    entity: "AMBIOS",
    category: "metrica",
    shortDef: "Ambos bancos MSCI AA. Bradesco Sustainalytics 14.9 (mejor) vs Credicorp 22.1.",
    fullDef: "ESG (Environmental, Social, Governance) mide sostenibilidad y responsabilidad corporativa. Ambos bancos tienen calificación MSCI ESG AA. Bradesco: Sustainalytics 14.9 (menor = menor riesgo). Credicorp: Sustainalytics 22.1 (2023), incluido en DJSI. Credicorp incorporó criterios ESG en compensación ejecutiva.",
    comparison: "Bradesco tiene mejor Sustainalytics (14.9 vs 22.1) — menor riesgo ESG. Ambos MSCI AA. Credicorp en DJSI. Ambos cumplen Tier A de integración ESG. Bradesco mejor posicionado en riesgo ESG pero con cautela por desfase temporal.",
    estado: "COMPARABLE (mismo proveedor MSCI/Sustainalytics)",
    valor: "Bradesco MSCI AA, Sustainalytics 14.9 · Credicorp MSCI AA, Sustainalytics 22.1, DJSI",
    fuentes: ["S69 (MSCI Bradesco)", "S70 (MSCI Credicorp)"],
    confianza: "ALTA (VERIFIED)",
  },
  "CAPITAL_INCREASE": {
    id: "CAPITAL_INCREASE",
    term: "Aumento de capital R$10B",
    entity: "BRADESCO",
    category: "metrica",
    shortDef: "Bradesco aprobó aumento de capital de R$10B (jul/2026). Controladores comprometen R$8B.",
    fullDef: "El 29 de julio de 2026, el Consejo de Bradesco aprobó aumento de capital de hasta R$10B mediante suscripción privada para accionistas existentes. Controladores (Cidade de Deus, Fundação Bradesco, NCF Participações) comprometen R$8B. JCP de R$6.5B adelantado. Capital Principal +0.9pp a ~12.7% pro forma.",
    comparison: "BCP mantiene ratio de Capital Global de 19.44% (FY2025, SBS) con fortalecimiento orgánico gradual (14.43% en 2022 → 19.44% en 2025) sin necesidad de inyección extraordinaria. Bradesco recurrió a aumento de capital puntual. Diferencia real documentada, aunque métricas no directamente comparables (Capital Principal vs Capital Global).",
    estado: "VERIFIED (jul/2026, comunicado CVM/mercado)",
    valor: "R$10B aumento · R$8B controladores · Capital Principal +0.9pp ~12.7% pro forma",
    fuentes: ["S24 (Crypto Briefing)", "S58 (Bradesco RI)"],
    confianza: "ALTA (INDEPENDENTLY_CORROBORATED)",
  },

  // === INCLUSIÓN Y EDUCACIÓN FINANCIERA ===
  "MEU_BOLSO": {
    id: "MEU_BOLSO",
    term: "Meu Bolso em Dia",
    entity: "BRADESCO",
    category: "iniciativa",
    shortDef: "Plataforma de educación financiera gratuita de Bradesco. Diagnóstico financiero + trilhas de aprendizaje personalizadas.",
    fullDef: "Meu Bolso em Dia es una plataforma de educación financiera gratuita de Banco Bradesco, disponible online para cualquier ciudadano brasileño. Ofrece diagnóstico gratuito de situación financiera y trilhas de aprendizaje personalizadas con cursos, contenidos y herramientas organizadas por educadores. Fruto de partnership con FEBRABAN. Impacto documentado en jul/2025 (LinkedIn).",
    comparison: "BCP tiene programas de educación financiera propios ('nuestros programas de educación financiera buscan que las personas adopten comportamientos financieros saludables') e inclusión vía Yape (541K personas con primer crédito en 2024) y Mibanco (4.1M personas incluidas). Ambos bancos tienen programas de educación/inclusión financiera, pero Bradesco tiene una plataforma digital dedicada (Meu Bolso em Dia) mientras BCP integra educación en su memoria y programas sociales.",
    estado: "PRODUCTION (plataforma online activa, impacto documentado 2025)",
    valor: "Educación financiera gratuita · diagnóstico personalizado · trilhas de aprendizaje · inclusión financiera",
    fuentes: ["banco.bradesco (official)", "cmsarquivos.febraban.org.br (FEBRABAN guide)", "pt.linkedin.com (impact jul/2025)"],
    confianza: "ALTA (VERIFIED)",
  },
  "CIDADANIA_FINANCEIRA": {
    id: "CIDADANIA_FINANCEIRA",
    term: "Cidadania Financeira",
    entity: "BRADESCO",
    category: "iniciativa",
    shortDef: "Programa de inclusión y educación financiera de Bradesco para grupos desfavorecidos. Promueve igualdad de oportunidades.",
    fullDef: "Cidadania Financeira es el programa de inclusión y educación financiera de Banco Bradesco. Capacita grupos desfavorecidos social y económicamente para promover inclusión financiera e igualdad de oportunidades. Incluye planeamiento para el futuro, promoviendo salud financiera.",
    comparison: "BCP tiene programas equivalentes de inclusión financiera premiados por SBS (SMA 2025). BCP incluyó 541K personas via Yape (2024) y Mibanco incluyó 4.1M personas (56% mujeres). Ambos bancos tienen compromiso con inclusión financiera, pero BCP/Credicorp tiene ventaja estructural con Mibanco (microfinanzas dedicadas) que Bradesco no replica.",
    estado: "PRODUCTION (programa activo, guía por pilares fundamentales)",
    valor: "Inclusión financiera grupos desfavorecidos · igualdad de oportunidades · salud financiera",
    fuentes: ["banco.bradesco (official)"],
    confianza: "ALTA (VERIFIED)",
  },
  "FUNDACAO_BRADESCO": {
    id: "FUNDACAO_BRADESCO",
    term: "Fundação Bradesco",
    entity: "BRADESCO",
    category: "iniciativa",
    shortDef: "Fundación educativa de Bradesco (1956). Combate analfabetismo con escuelas y educación online gratuita (Escola Virtual).",
    fullDef: "Fundação Bradesco fue establecida en 1956 por Bradesco para combatir el analfabetismo. Impulsada por utilidades de Bradesco Seguros. Ofrece educación financiera via Escola Virtual (cursos online gratuitos) y red de escuelas propias. Es uno de los programas sociales más antiguos y estructurados de la banca brasileña.",
    comparison: "BCP no tiene una fundación educativa equivalente a Fundação Bradesco (1956, +70 años). BCP tiene programas de educación financiera pero no una fundación dedicada con red de escuelas propias. Bradesco tiene ventaja estructural en educación social con Fundação Bradesco.",
    estado: "PRODUCTION (desde 1956, activa)",
    valor: "Combate analfabetismo · red de escuelas · Escola Virtual · educación financiera gratuita",
    fuentes: ["encyclopedia.com", "fundacao.bradesco", "ev.org.br"],
    confianza: "ALTA (VERIFIED)",
  },
  "BCP_EDUCACION": {
    id: "BCP_EDUCACION",
    term: "Educación Financiera BCP",
    entity: "BCP",
    category: "iniciativa",
    shortDef: "Programas de educación e inclusión financiera de BCP. Premiados por SBS (SMA 2025). Incluye 541K personas via Yape.",
    fullDef: "BCP tiene programas de educación e inclusión financiera que buscan que las personas, negocios y sociedad adopten comportamientos financieros saludables. La SBS premió las mejores prácticas de inclusión financiera de BCP durante la SMA 2025. BCP incluyó 541K personas en el sistema financiero via Yape (2024) y Mibanco incluyó 4.1M personas (56% mujeres). La Memoria Integrada BCP documenta estos esfuerzos.",
    comparison: "Bradesco tiene Fundação Bradesco (1956, red de escuelas + Escola Virtual) y Meu Bolso em Dia (plataforma digital de educación financiera gratuita). BCP tiene programas premiados por SBS e inclusión via Yape/Mibanco. Ambos bancos comprometidos con inclusión/educación, pero con enfoques distintos: Bradesco con fundación educativa estructurada, BCP con inclusión via productos digitales (Yape) y microfinanzas (Mibanco).",
    estado: "PRODUCTION (programa activo, premiado por SBS 2025)",
    valor: "541K personas incluidas via Yape (2024) · SBS premió mejores prácticas · educación financiera",
    fuentes: ["grupocredicorp.com", "viabcp.com (Memoria Integrada)", "facebook.com (SBS award)"],
    confianza: "ALTA (VERIFIED)",
  },

  // === TÉRMINOS ADICIONALES ===
  "SLM": {
    id: "SLM",
    term: "SLM (Small Language Model)",
    entity: "SISTEMA",
    category: "tecnologia",
    shortDef: "Modelos de lenguaje pequeños. No se encontró evidencia pública específica de Bradesco o BCP usando SLMs.",
    fullDef: "SLM (Small Language Model) se refiere a modelos de lenguaje de menor escala comparados con LLMs grandes. Pueden ejecutarse on-device o en edge. No se encontró evidencia pública específica de Bradesco o BCP implementando SLMs. Bradesco usa multi-LLM en Bridge pero no especifica si incluye SLMs.",
    comparison: "Ningún banco publica evidencia específica de uso de SLMs. Ambos están clasificados como UNKNOWN en esta dimensión.",
    estado: "UNKNOWN (no evidencia pública específica de ningún banco)",
    valor: "No verificado",
    fuentes: [],
    confianza: "BAJA (UNRESOLVED)",
  },
  "GNN": {
    id: "GNN",
    term: "GNN (Graph Neural Network)",
    entity: "SISTEMA",
    category: "tecnologia",
    shortDef: "Redes neuronales para datos estructurados en grafos. No se encontró evidencia pública específica de Bradesco o BCP.",
    fullDef: "GNN (Graph Neural Network) es una técnica de ML diseñada para datos estructurados en grafos, ideal para detección de fraude mediante análisis de redes de transacciones. Es estándar de la industria (NVIDIA, Neo4j, TigerGraph ofrecen soluciones) pero NO se encontró evidencia pública específica de Bradesco o BCP implementando GNNs. Bradesco usa FICO Platform para fraude (25M Pix tx/día, -89% revisiones) pero FICO no publicly disclose usar GNN específicamente.",
    comparison: "Ningún banco publica evidencia específica de uso de GNNs. Bradesco tiene FICO SAFER para fraude (PRODUCTION) y BCP tiene Lynx Tech (-30% fraude, Deep Learning + RNN). Ambos tienen IA de fraude en producción pero no confirman GNN específicamente. Permanece UNKNOWN.",
    estado: "UNKNOWN (estándar de industria pero no confirmado para ningún banco)",
    valor: "No verificado — potencial para detección de fraude por red de transacciones",
    fuentes: [],
    confianza: "BAJA (UNRESOLVED — PendingRecord)",
  },
  "SYNTHETIC_DATA": {
    id: "SYNTHETIC_DATA",
    term: "Synthetic Data",
    entity: "SISTEMA",
    category: "tecnologia",
    shortDef: "Datos generados artificialmente para entrenar modelos de IA sin exponer datos sensibles. No confirmado para ningún banco.",
    fullDef: "Synthetic Data se refiere a datos generados artificialmente por IA para entrenar modelos de ML sin exponer información personal sensible (cumplimiento LGPD/GDPR). Empresas como MOSTLY AI, Gretel, DataCebo ofrecen soluciones. NO se encontró evidencia pública específica de Bradesco o BCP usando synthetic data. La ANPD brasileña publicó estudio sobre IA generativa y protección de datos (jun/2025) que podría incentivar adopción.",
    comparison: "Ningún banco publica evidencia específica de uso de synthetic data. Ambos están clasificados como UNKNOWN. La regulación brasileña (LGPD/ANPD) y peruana podrían incentivar adopción futura. Permanece UNKNOWN.",
    estado: "UNKNOWN (no evidencia pública específica de ningún banco)",
    valor: "No verificado — potencial para entrenamiento de modelos con cumplimiento de privacidad",
    fuentes: [],
    confianza: "BAJA (UNRESOLVED — PendingRecord)",
  },
  "ADVERSARIAL_ML": {
    id: "ADVERSARIAL_ML",
    term: "Adversarial ML",
    entity: "SISTEMA",
    category: "tecnologia",
    shortDef: "Ataques y defensas contra modelos de ML. NIST publicó guía (2025). No confirmado para ningún banco específicamente.",
    fullDef: "Adversarial ML se refiere a ataques diseñados para engañar modelos de ML (evasion, poisoning, model stealing) y las defensas contra ellos. NIST publicó guía técnica (mar/2025). Bradesco tiene 7 Guardrails en Bridge que podrían incluir protecciones adversariales, pero no se confirma específicamente. BCP no publica evidencia de adversarial ML defenses.",
    comparison: "Ningún banco publica evidencia específica de adversarial ML defenses. Bradesco tiene 7 Guardrails en Bridge (podrían incluir protecciones adversariales pero no se confirma). NIST publicó guía 2025. Permanece UNKNOWN para ambos bancos.",
    estado: "UNKNOWN (NIST publicó guía 2025 pero no confirmado para ningún banco)",
    valor: "No verificado — potencial para robustez de modelos de IA",
    fuentes: ["NIST Technical Series Publication (mar/2025)"],
    confianza: "BAJA (UNRESOLVED — PendingRecord)",
  },
  "CLARA": {
    id: "CLARA",
    term: "Clara",
    entity: "BCP",
    category: "iniciativa",
    shortDef: "Asistente virtual de BCP con IA generativa. Disponible en WhatsApp (993-119-898). Equivalente funcional de BIA de Bradesco.",
    fullDef: "Clara es la asistente virtual de Banco de Crédito del Perú (BCP), lanzada en julio 2024 en la Banca por Teléfono. En enero 2025 se actualizó con IA Generativa. Disponible vía WhatsApp (993-119-898) y web. Resuelve consultas de saldos, movimientos, tarjetas de crédito, número de cuenta, productos y servicios 24/7. Clara aprende de cada conversación y se adapta a preferencias del usuario (personalización). BCP es la primera empresa del grupo Credicorp en implementar IA generativa en voz para atención de clientes.",
    comparison: "Clara (BCP) es el equivalente funcional directo de BIA (Bradesco). Ambas son asistentes virtuales con IA generativa. BIA: 24M+ usuarios, 90% retención, evolución Watson→GenAI (2016-2025). Clara: lanzada jul/2024, IA Gen desde ene/2025, disponible WhatsApp + Banca por Teléfono + web. BIA tiene mayor escala documentada (24M+ vs Clara sin métrica pública de usuarios). Ambas son PRODUCTION_SCALING. Diferencia clave: BIA tiene 10 años de evolución (2016-2026), Clara tiene 2 años (2024-2026).",
    estado: "PRODUCTION_SCALING (IA Gen desde ene/2025, disponible WhatsApp + web + Banca por Teléfono)",
    valor: "Atención 24/7 vía WhatsApp · personalización · consulta saldos/movimientos · resolución consultas · primera IA Gen voice en Credicorp",
    fuentes: ["viabcp.com (official)", "facebook.com (BCP official)", "peru-retail.com (oct/2024)", "semanaeconomica.com (ene/2025)", "es.linkedin.com", "corresponsables.com (jul/2024)"],
    confianza: "ALTA (INDEPENDENTLY_CORROBORATED)",
  },
};

// Helper function to get context by term
export function getContext(term: string): ContextEntry | undefined {
  const normalized = term.toUpperCase().replace(/\s+/g, "_");
  return CONTEXT_REGISTRY[normalized] || CONTEXT_REGISTRY[term];
}
