// Context Registry — Additional context for user-facing elements
// Provides drill-down info on hover/click/tap for claims, terms, sections, and points

export interface ContextEntry {
  id: string;
  term: string;
  entity: "BRADESCO" | "BCP" | "CREDICORP" | "AMBIOS" | "SISTEMA";
  category: "iniciativa" | "producto" | "tecnologia" | "metrica" | "termino" | "regulacion";
  shortDef: string;
  fullDef: string;
  comparison?: string;
  estado?: string;
  valor?: string;
  fuentes?: string[];
  confianza?: string;
}

export const CONTEXT_REGISTRY: Record<string, ContextEntry> = {
  // === BRADESCO INICIATIVAS ===
  "BIA": {
    id: "BIA",
    term: "BIA",
    entity: "BRADESCO",
    category: "iniciativa",
    shortDef: "Asistente virtual de Bradesco lanzado en 2016 sobre IBM Watson, hoy 100% GenAI.",
    fullDef: "BIA (Bradesco Inteligência Artificial) es el asistente virtual de Banco Bradesco S.A. Lanzado en 2016 sobre IBM Watson — primera empresa en Brasil en entrenar Watson. Evolucionó a 100% IA generativa en 2025. Procesa voz y texto en app, WhatsApp y web. 24M+ usuarios, 90% retención de demandas digitales, ~40× reducción de costo de atención.",
    comparison: "BCP tiene un asistente virtual en la Banca Móvil BCP, pero no publica métricas de retención equivalentes. La escala de BIA (24M+ usuarios, 90% retención) es superior a cualquier asistente público de BCP documentado.",
    estado: "PRODUCTION_SCALING",
    valor: "24M+ usuarios · 90% retención · ~40× reducción costo atención · 82% resolución primer nivel",
    fuentes: ["S49 (IBM Newsroom)", "S31 (Microsoft)", "S03 (Earnings call 4T25)"],
    confianza: "ALTA (INDEPENDENTLY_CORROBORATED)",
  },
  "BRIDGE": {
    id: "BRIDGE",
    term: "Bridge",
    entity: "BRADESCO",
    category: "iniciativa",
    shortDef: "Plataforma corporativa de IA generativa de Bradesco con multi-LLM, RAG, 7 guardrails.",
    fullDef: "Bridge ('Bradesco Inteligência de Data Generativa') es la plataforma corporativa de GenAI de Banco Bradesco S.A., lanzada en junio 2025. Arquitectura: multi-LLM (múltiples proveedores), RAG (Retrieval-Augmented Generation), 7 Guardrails de seguridad (PII, filtros, compliance), multi-cloud (Azure/AWS/Oracle). 500+ casos de uso en producción, 70 a escala. Conecta datos, modelos, agentes y canales.",
    comparison: "BCP tiene GenIA (herramienta de IA generativa de Credicorp), pero no hay conteo público de casos de uso comparable a los 500 de Bridge. Bradesco comunica mayor granularidad en su plataforma GenAI que BCP.",
    estado: "PRODUCTION",
    valor: "500+ casos de uso · 70 a escala · +35% productividad con Copilot · lead time -43%",
    fuentes: ["S04 (CTO interview)", "S18 (Forbes Brasil)", "S50 (StartSe)", "S51 (DIO)", "S57 (Convergencia Digital)"],
    confianza: "ALTA (INDEPENDENTLY_CORROBORATED)",
  },
  "NEXT": {
    id: "NEXT",
    term: "Next",
    entity: "BRADESCO",
    category: "iniciativa",
    shortDef: "Banco digital de Bradesco para público joven, lanzado 2017, reincorporado al banco matriz 2023-2024.",
    fullDef: "Next fue el primer banco 100% digital de Bradesco, lanzado en junio 2017 para público joven. Alcanzó 10M+ clientes (ene/2022) con Next Shop marketplace (cashback). Reincorporado al banco matriz como segmento de atención (fines 2023-2024) — decisión consciente, NO un fracaso. App sigue activo (Google Play jun/2026).",
    comparison: "BCP no tiene un banco digital separado equivalente a Next. Yape (BCP) cumple parcialmente la función de captura de público digital, pero es una app de pagos, no un banco 100% digital. La reincorporación de Next sugiere que Bradesco consolidó su estrategia digital en el banco matriz.",
    estado: "INTEGRATED (no sunset, no fracaso)",
    valor: "10M+ clientes (2022) · Next Shop marketplace · aprendizaje digital · infraestructura Azure",
    fuentes: ["S44 (O Globo)", "S10 (Google Play)", "S40 (TikTok presence)"],
    confianza: "ALTA (INDEPENDENTLY_CORROBORATED)",
  },
  "BITZ": {
    id: "BITZ",
    term: "Bitz",
    entity: "BRADESCO",
    category: "iniciativa",
    shortDef: "Cartera digital de Bradesco lanzada 2020, cerrada 2023 (absorbida por Digio).",
    fullDef: "Bitz fue una cartera digital de Bradesco lanzada en sep/2020 (cartão virtual Elo, cartão físico débito, QR Code). Meta: 25% del segmento en 3 años. Adquirió fintech 4ward en dic/2020. Formalmente absorbida por Digio en mar/2023 — sunset consciente de consolidación, no fracaso de producto.",
    comparison: "BCP tiene Yape como su cartera/app de pagos — Yape escaló a 20M+ usuarios y se convirtió en superapp, mientras Bitz fue absorbida por Digio. La diferencia de trayectoria (Yape escaló, Bitz fue consolidada) refleja contextos de mercado distintos: Brasil tenía Pix como sistema nacional, mientras Perú necesitaba una solución privada como Yape.",
    estado: "SUNSET (mar/2023, absorbida por Digio)",
    valor: "Experimento de captura de segmento no bancarizado; consolidado en Digio",
    fuentes: ["S41 (Estadão)", "S42 (Mobile Time)", "S43 (Finsiders)"],
    confianza: "ALTA (INDEPENDENTLY_CORROBORATED)",
  },
  "INOVABRA": {
    id: "INOVABRA",
    term: "Inovabra",
    entity: "BRADESCO",
    category: "iniciativa",
    shortDef: "Habitat de co-innovación de Bradesco en São Paulo (22.000 m²), 230 startups, 80 empresas, 8 hubs.",
    fullDef: "Inovabra habitat es un espacio físico de co-innovación de Organização Bradesco, inaugurado en feb/2018 (22.000 m², São Paulo, con WeWork). Conecta startups con producto maduro, corporaciones y hubs. 230 startups, 80 empresas, 8 hubs (2026). Inovabra Ventures: R$400M fondo propio (40% inversiones PE del banco). Startups +55% faturamento (2019). 500 contratos firmados (2021).",
    comparison: "BCP tiene CIX (Centro de Innovación del BCP) con +1 década de operación — es un laboratorio interno, no un habitat abierto como Inovabra. Modelos distintos: Inovabra es co-innovación abierta con startups externas; CIX es exploración→ideación→creación interna. Krealo (Credicorp) es el CVC equivalente a Inovabra Ventures.",
    estado: "MATURE_PRODUCTION",
    valor: "230 startups · R$400M fondo · +55% revenue startups · 500 contratos · 65K visitantes (2019)",
    fuentes: ["S08 (Inovabra official)", "S25 (Finsiders)", "S26 (Mobile Time)", "S27 (CEBDS)"],
    confianza: "ALTA (VERIFIED)",
  },
  "DIGIO": {
    id: "DIGIO",
    term: "Digio",
    entity: "BRADESCO",
    category: "iniciativa",
    shortDef: "Banco digital subsidiario de Bradesco (100% desde 2021-2022), infraestructura AWS separada.",
    fullDef: "Banco Digio S.A. es un banco digital subsidiario de Banco Bradesco S.A. Inicialmente JV con Banco do Brasil (50/50). Bradesco compró el 49,99% restante por R$625M en 2021-2022. Infraestructura en AWS (separada de Next/Azure). Management declaró intención de mantenerlo como unidad independiente. Absorbió clientes de Bitz en 2023.",
    comparison: "BCP no tiene un banco digital subsidiario equivalente a Digio. La estrategia de Bradesco de mantener dos infraestructuras cloud separadas (Next/Azure + Digio/AWS) no tiene equivalente público en BCP.",
    estado: "PRODUCTION",
    valor: "R$625M adquisición · infraestructura AWS independiente · absorbió clientes Bitz",
    fuentes: ["S06 (multicloud announcement)", "S01 (20-F)"],
    confianza: "ALTA (INDEPENDENTLY_CORROBORATED)",
  },
  "DREX": {
    id: "DREX",
    term: "Drex",
    entity: "BRADESCO",
    category: "tecnologia",
    shortDef: "Piloto de real digital (CBDC) del Banco Central do Brasil. Bradesco participa. BC pivotó sin blockchain 2026.",
    fullDef: "Drex es el real digital del Banco Central do Brasil (CBDC). Bradesco participa en el piloto probando préstamos con garantías tokenizadas, debêntures digitales y crédito colateralizado en CDB mediante smart contracts. En ago/2025, el BC anunció que Drex abandonará blockchain/DLT en su fase de corto plazo, lanzando versión simplificada sin tokenización para 2S2026.",
    comparison: "BCP/Yape participa en el piloto CBDC del BCRP (Perú) con 107K usuarios y 41K tx/diarias. Ambos bancos experimentan con CBDC pero en contextos regulatorios distintos: Drex (Brasil, BC pivotó sin blockchain) vs BCRP CBDC (Perú, piloto activo con Yape).",
    estado: "EXPERIMENT (BC pivotó Drex sin blockchain para fase corta 2026)",
    valor: "Aprendizaje de tokenización y smart contracts; horizonte incierto tras pivote del BC",
    fuentes: ["S61 (BCB)"],
    confianza: "ALTA (INDEPENDENTLY_CORROBORATED)",
  },

  // === BCP INICIATIVAS ===
  "YAPE": {
    id: "YAPE",
    term: "Yape",
    entity: "BCP",
    category: "iniciativa",
    shortDef: "App de pagos/superapp de BCP Perú. 20M+ usuarios, 15M+ MAU, ~75% población Perú.",
    fullDef: "Yape es la app de pagos móviles de Banco de Crédito del Perú (BCP), lanzada en feb/2017. Evolucionó de billetera digital a superapp. Permite pagos QR, transferencias P2P, recargas, pago de servicios. No requiere cuenta bancaria BCP. 20M+ usuarios totales, 15M+ MAU, ~75% de la población de Perú, 23M+ usuarios diarios. Tercera app más usada en Perú (McKinsey). Breakeven alcanzado con 12.3M+ usuarios. 541K personas recibieron primer crédito via Yape (2024).",
    comparison: "Bradesco tiene Pix (sistema nacional de pagos instantáneos) que procesa 68.7B transacciones/año — pero Pix es infraestructura nacional obligatoria, no una app de un banco. Yape es un producto de BCP que cumple una función similar a Pix pero en un mercado sin sistema nacional equivalente. Next (Bradesco) tenía 10M+ clientes antes de reincorporación — Yape (20M+) tiene mayor escala.",
    estado: "PRODUCTION_SCALING",
    valor: "20M+ users · 15M+ MAU · ~75% pop. Perú · 23M+ daily · 541K primer crédito · 65% ingresos disrupción grupo",
    fuentes: ["S47 (Credicorp)", "S54 (Nuvei)", "S55 (McKinsey)", "S12 (Credicorp IR)"],
    confianza: "ALTA (INDEPENDENTLY_CORROBORATED)",
  },
  "CRIPTOCOCOS": {
    id: "CRIPTOCOCOS",
    term: "CriptoCocos",
    entity: "BCP",
    category: "iniciativa",
    shortDef: "Primera plataforma bancaria de criptoactivos del Perú. Bitcoin + USDC. Sandbox SBS. ~3.000 clientes.",
    fullDef: "CriptoCocos es la primera plataforma bancaria de criptoactivos del Perú, lanzada por BCP en oct/2025. Permite comprar/vender Bitcoin y USDC con custodia institucional de BitGo. Autorizada por SBS dentro del sandbox regulatorio. Limitada a ~3.000 clientes en fase piloto. BCP es el único banco peruano con un proyecto de esta naturaleza.",
    comparison: "Bradesco no tiene un producto de cripto retail equivalente a CriptoCocos. Bradesco experimenta con Drex (CBDC) y tiene partnership con Parfin para stablecoins cross-border, pero no ofrece compra/venta de Bitcoin/USDC a clientes retail como BCP. BCP está ADELANTE de Bradesco en cripto retail regulado.",
    estado: "PILOT (sandbox SBS, ~3.000 clientes)",
    valor: "Posicionamiento pionero cripto bancario LatAm · aprendizaje regulatorio · acceso regulado a cripto",
    fuentes: ["S62 (BitGo)", "S63 (BusinessWire)"],
    confianza: "ALTA (INDEPENDENTLY_CORROBORATED)",
  },
  "CIX": {
    id: "CIX",
    term: "CIX",
    entity: "BCP",
    category: "iniciativa",
    shortDef: "Centro de Innovación del BCP, +1 década activo. Proceso: Exploración→Ideación→Creación.",
    fullDef: "CIX (Centro de Innovación del BCP) es un laboratorio interno de BCP con más de una década de operación. Sigue el proceso: Exploración → Ideación → Creación. Activo en 2025 (#InnovationDay2025). No es un proyecto histórico de GitHub — es un centro de innovación en operación continua.",
    comparison: "Bradesco tiene Inovabra habitat (espacio físico 22.000 m², 230 startups, co-innovación abierta con WeWork). CIX es un laboratorio interno (no habitat abierto). Modelos distintos: Inovabra es co-innovación con startups externas; CIX es exploración interna. Ambos son MATURE/PRODUCTION.",
    estado: "MATURE_PRODUCTION (+1 década activo)",
    valor: "Innovación interna continua · cultura de aprendizaje · #InnovationDay2025",
    fuentes: ["S36 (Instagram @cix.bcp)", "S37 (Viabcp)"],
    confianza: "ALTA (INDEPENDENTLY_CORROBORATED)",
  },
  "GENIA": {
    id: "GENIA",
    term: "GenIA",
    entity: "BCP",
    category: "iniciativa",
    shortDef: "Herramienta de IA generativa de Credicorp/BCP. Pionero en Perú en IA gen para software.",
    fullDef: "GenIA es la herramienta de IA generativa de Credicorp/BCP. BCP es pionero en Perú en uso de IA generativa para desarrollar software (Forbes Perú, dic/2024), con marco de 10+ prácticas (revisiones código, pruebas automatizadas). También implementa GenAI en voz para atención de clientes (ene/2025). AI Automation Specialist en Credicorp Capital.",
    comparison: "Bradesco tiene Bridge (500+ casos de uso, multi-LLM, RAG, 7 guardrails) — plataforma más documentada públicamente. GenIA de BCP no tiene conteo público de casos de uso comparable. Bradesco comunica mayor granularidad, pero BCP fue pionero en Perú en IA gen para software.",
    estado: "PRODUCTION",
    valor: "Pionero Perú IA gen software · marco 10+ prácticas · GenAI voice atención clientes",
    fuentes: ["S28 (Forbes Perú)", "S30 (Credicorp GenIA)", "S33 (Credicorp 4Q25)"],
    confianza: "ALTA (INDEPENDENTLY_CORROBORATED)",
  },
  "BCP_XPLORE": {
    id: "BCP_XPLORE",
    term: "BCP Xplore",
    entity: "BCP",
    category: "iniciativa",
    shortDef: "Unidad de Open Banking/APIs de BCP. Recaudación, pagos automáticos, financiamiento flexible.",
    fullDef: "BCP Xplore es la unidad de Open Banking/APIs de Banco de Crédito del Perú. Ofrece servicios de recaudación, pagos automáticos y financiamiento flexible exclusivos para clientes del programa. Es la respuesta de BCP al ecosistema Open Banking peruano.",
    comparison: "Bradesco es participante obligatorio de Open Finance Brasil (BACEN, desde 2021) — marco más maduro que el peruano. BCP Xplore es una iniciativa propia de Open Banking, mientras Bradesco cumple con el marco obligatorio BACEN. Diferencia regulatoria: Brasil tiene Open Finance obligatorio; Perú está en desarrollo.",
    estado: "PRODUCTION",
    valor: "APIs de recaudación · pagos automáticos · financiamiento flexible · ecosistema fintech",
    fuentes: ["S15 (BCP Xplore official)"],
    confianza: "ALTA (VERIFIED)",
  },

  // === CREDICORP INICIATIVAS ===
  "KREALO": {
    id: "KREALO",
    term: "Krealo",
    entity: "CREDICORP",
    category: "iniciativa",
    shortDef: "Fondo de venture corporativo de Credicorp. 16 startups en portfolio. Expansión a Ecuador.",
    fullDef: "Krealo es el fondo de Corporate Venture Capital (CVC) de Credicorp Ltd. Enfoque 'hands-on' tipo VC. Portfolio regional de 16 startups, foco en fintech AI solutions. 8 transacciones en 2025. Expansión a Ecuador con inversión en Jelou (mar/2026). Tenpo autorizado como banco en Chile (ene/2026).",
    comparison: "Bradesco tiene Inovabra Ventures (R$400M fondo propio, 40% de inversiones PE del banco) — equivalente funcional a Krealo. Ambos son CVC con enfoque fintech. Krealo tiene 16 startups en portfolio; Inovabra Ventures no publica conteo equivalente pero tiene R$400M de capital.",
    estado: "PRODUCTION",
    valor: "16 startups · 8 transacciones 2025 · expansión Ecuador · Tenpo primer neobanco Chile",
    fuentes: ["S46 (Krealo)", "S56 (Krealo insights)"],
    confianza: "ALTA (INDEPENDENTLY_CORROBORATED)",
  },
  "TENPO": {
    id: "TENPO",
    term: "Tenpo",
    entity: "CREDICORP",
    category: "iniciativa",
    shortDef: "Fintech/neobanco de Credicorp en Chile. Primer neobanco autorizado en Chile (ene/2026). 754K clientes.",
    fullDef: "Tenpo es una fintech impulsada por Krealo (Credicorp) en Chile. En enero de 2026 se convirtió en el primer neobanco autorizado en Chile. Cuenta digital $0, tarjeta Mastercard. 754K clientes (fin 2024). Inicio de operaciones bancarias previsto para 1S2026.",
    comparison: "Bradesco no tiene un neobanco internacional equivalente a Tenpo. Next (Bradesco) era un banco digital doméstico (Brasil) que fue reincorporado. Tenpo representa la expansión internacional de Credicorp fuera de Perú — algo que Bradesco no ha hecho públicamente con marcas digitales.",
    estado: "PRODUCTION (primer neobanco Chile, ene/2026)",
    valor: "754K clientes · primer neobanco Chile · expansión internacional Credicorp",
    fuentes: ["S56 (Krealo)", "Credicorp Annual Report 2024"],
    confianza: "ALTA (INDEPENDENTLY_CORROBORATED)",
  },
  "MIBANCO": {
    id: "MIBANCO",
    term: "Mibanco",
    entity: "CREDICORP",
    category: "iniciativa",
    shortDef: "Líder de microfinanzas en Perú (Credicorp). 4.1M personas incluidas, 56% mujeres.",
    fullDef: "Mibanco es el líder de microfinanzas en Perú, subsidiaria de Credicorp. Incluyó a 4.1M personas en el sistema financiero. 64K clientes (56% mujeres). S/108.5M desembolsados a 63.6K clientes. Modelo de agencia compartida con BCP (ej: Órganos).",
    comparison: "Bradesco NO tiene un equivalente de microfinanzas. Mibanco es una ventaja estructural de Credicorp en inclusión financiera que Bradesco no replica. Esta es una dimensión donde BCP/Credicorp es estructuralmente más fuerte.",
    estado: "PRODUCTION",
    valor: "4.1M personas incluidas · 64K clientes (56% mujeres) · S/108.5M desembolsados · líder microfinanzas Perú",
    fuentes: ["S81 (Grupo Credicorp)"],
    confianza: "ALTA (VERIFIED)",
  },

  // === TECNOLOGÍAS ===
  "PIX": {
    id: "PIX",
    term: "Pix",
    entity: "BRADESCO",
    category: "tecnologia",
    shortDef: "Sistema nacional de pagos instantáneos de Brasil (BACEN, 2020). 68.7B transacciones en 2024.",
    fullDef: "Pix es el sistema nacional de pagos instantáneos del Banco Central do Brasil (BACEN), lanzado en noviembre 2020. Bradesco es institución participante. 68.7B transacciones en 2024 (+52% YoY). USD 6.7T volumen proyectado 2025. 8B transacciones mensuales.",
    comparison: "Perú no tiene un sistema nacional equivalente a Pix. Yape (BCP) cumple parcialmente esa función pero es una app de un banco, no un sistema nacional obligatorio. La madurez de Pix (Brasil) vs la ausencia de equivalente nacional (Perú) explica parte de la diferencia en casos de uso digital observable (hipótesis H4).",
    estado: "MATURE (sistema nacional obligatorio desde 2020)",
    valor: "68.7B tx/año (2024) · USD 6.7T volumen proyectado 2025 · 8B tx mensuales",
    fuentes: ["S82 (BCB)"],
    confianza: "ALTA (VERIFIED)",
  },
  "OPEN_FINANCE": {
    id: "OPEN_FINANCE",
    term: "Open Finance",
    entity: "BRADESCO",
    category: "regulacion",
    shortDef: "Marco regulatorio obligatorio de Open Finance en Brasil (BACEN, desde 2021). Bradesco participa.",
    fullDef: "Open Finance Brasil es un marco regulatorio obligatorio del Banco Central do Brasil (BACEN) desde 2021. Bradesco es institución participante activa. Permite a clientes compartir datos financieros entre instituciones mediante APIs estandarizadas.",
    comparison: "Perú no tiene un marco de Open Finance obligatorio equivalente al brasileño. BCP Xplore es una iniciativa propia de Open Banking, no un cumplimiento regulatorio. Diferencia regulatoria: Brasil obligatorio desde 2021; Perú en desarrollo.",
    estado: "MATURE (obligatorio BACEN desde 2021)",
    valor: "APIs estandarizadas · interoperabilidad · portabilidad de datos · ecosistema fintech",
    fuentes: ["S38 (Bradesco Open Finance page)"],
    confianza: "ALTA (VERIFIED)",
  },
  "FICO": {
    id: "FICO",
    term: "FICO Platform",
    entity: "AMBIOS",
    category: "tecnologia",
    shortDef: "Plataforma de decisioning/fraude usada por AMBOS bancos (Bradesco y BCP).",
    fullDef: "FICO Platform es una solución de decisioning y detección de fraude usada por ambos bancos. Bradesco: SAFER/FICO procesa 25M transacciones Pix/día, -89% revisiones manuales, -25% rechazos. BCP: usa FICO para maximizar rentabilidad, reducir carga operativa, onboarding nuevos segmentos.",
    comparison: "AMBOS bancos (Bradesco y BCP) usan FICO Platform — mismo vendor para fraud/decisioning. Bradesco documenta outcomes más específicos (25M tx/día, -89% revisiones). BCP también implementa Lynx Tech AI (-30% fraude documentado). La adopción de FICO es una similitud tecnológica clave entre ambos bancos.",
    estado: "PRODUCTION (ambos bancos)",
    valor: "Bradesco: 25M tx/día, -89% revisiones · BCP: rentabilidad, onboarding segmentos",
    fuentes: ["S32 (FICO Bradesco)", "S72 (FICO SAFER detail)", "S84 (FICO BCP)"],
    confianza: "ALTA (STRONGLY_SUPPORTED)",
  },
};

// Helper function to get context by term
export function getContext(term: string): ContextEntry | undefined {
  const normalized = term.toUpperCase().replace(/\s+/g, "_");
  return CONTEXT_REGISTRY[normalized] || CONTEXT_REGISTRY[term];
}
