// SCIF — Bradesco × BCP data layer (Layer 0 + Layer 2 content)
// All material claims traceable to research/bradesco/ artifacts.
import type {
  SourceRecord, ClaimRecord, EntityRecord, TimelineEvent, ScaleEntity,
  TechnologyCapability, InitiativeRecord, RecommendationRecord,
  OpenQuestionRecord, ContradictionRecord, ModuleDef, BankSegment,
  ChannelMap, ProductEcosystemNode, PlatformRecord, RadarVersion,
} from "./types";

export const PROJECT = {
  title: "Bradesco × BCP Strategic Intelligence Command Center",
  framework: "StrategicCompanyIntelligenceFramework (SCIF) v1.0 · Solarize v2.2",
  primaryTarget: "Banco Bradesco S.A. (Brazil)",
  operatingComparator: "Banco de Crédito del Perú — BCP",
  groupComparator: "Credicorp Ltd. (where group-level comparison is valid)",
  outputLanguage: "Peruvian executive Spanish",
  asOf: "2026-01-15",
  independence: "Análisis estratégico independiente. No implica afiliación ni respaldo por parte de Bradesco, BCP o Credicorp.",
};

export const MODULES: ModuleDef[] = [
  { id: "exec", number: "00", title: "Centro de Comando Ejecutivo", subtitle: "Visión consolidada del dossier", icon: "LayoutDashboard", description: "Tablero ejecutivo: escala, rentabilidad, IA, innovación, comparación clave y preguntas abiertas en una sola pantalla." },
  { id: "history", number: "01", title: "Compañía, Perímetro e Historia", subtitle: "Estructura societaria y eras estratégicas", icon: "Building2", description: "Organização Bradesco, entidades, marcas, subsidiarias, M&A y línea temporal estratégica." },
  { id: "scale", number: "02", title: "Escala, Economía y Posición", subtitle: "Activos, rentabilidad, eficiencia", icon: "TrendingUp", description: "Scorecard de escala: activos, cartera, depósitos, ROAE, eficiencia. Bradesco vs BCP vs Credicorp." },
  { id: "customers", number: "03", title: "Clientes, Segmentos y Canales", subtitle: "Mapa de segmentos y canales", icon: "Users", description: "Segmentos (retail, affluent, private, SME, corporate) y canales (sucursales, app, WhatsApp, BIA, ATMs)." },
  { id: "products", number: "04", title: "Ecosistema de Productos", subtitle: "Cuentas, crédito, tarjetas, seguros", icon: "Package", description: "Mapa de productos y servicios: cuentas, depósitos, crédito, tarjetas, seguros, pensiones, wealth." },
  { id: "platforms", number: "05", title: "Plataformas Digitales y Journeys", subtitle: "Apps, wallets, asistentes, APIs", icon: "Smartphone", description: "Next, Digio, BIA, Bridge, BCP app, Yape, BCP Xplore. Estado actual de marcas históricas." },
  { id: "tech", number: "06", title: "Arquitectura Tecnológica", subtitle: "Multicloud, datos, ingeniería", icon: "Server", description: "Multicloud (Azure/AWS/Oracle), migración híbrida Teradata→Azure, ingeniería, productividad." },
  { id: "ai", number: "07", title: "IA, Datos y Tecnologías Emergentes", subtitle: "BIA, Bridge, GenAI, agentic, radar", icon: "BrainCircuit", description: "Capacidades de IA: BIA, Bridge, GenAI, agentic, datos sintéticos, quantum. Radar versionado." },
  { id: "innovation", number: "08", title: "Innovación, I+D y Open Innovation", subtitle: "Inovabra, cartera disruptiva, Krealo", icon: "Lightbulb", description: "Inovabra habitat, BCP Xplore, Yape/Tenpo/Krealo. Modelos de innovación comparados." },
  { id: "lifecycle", number: "09", title: "Ciclo de Vida de Iniciativas", subtitle: "Éxitos, experimentos, sunsets", icon: "GitBranch", description: "Next (INTEGRATED), Bitz (SUNSET), Digio, BIA, Bridge, Inovabra. Promesa original vs resultado." },
  { id: "partnerships", number: "10", title: "Alianzas, Startups y Adquisiciones", subtitle: "Red de socios y M&A", icon: "Handshake", description: "IBM, Azure, AWS, Oracle, Teradata, WeWork, startups Inovabra, Krealo portfolio, Culqi." },
  { id: "signals", number: "11", title: "Señales Externas", subtitle: "Clientes, empleados, talento", icon: "Radio", description: "Señales de app stores, Reclame Aqui, LinkedIn, empleos. Clasificadas por independencia." },
  { id: "risk", number: "12", title: "Riesgo, Regulación, Cyber y Resiliencia", subtitle: "Fraude, AML, identidad digital", icon: "ShieldCheck", description: "Open Finance Brasil, Pix, SBS Perú, biometría, fraude, AML, cyber, identidad digital." },
  { id: "compare", number: "13", title: "Bradesco vs BCP", subtitle: "Comparación estratégica", icon: "Scale", description: "Gate de comparabilidad. Comparación A (banco vs banco) y B (grupo vs grupo). Hipótesis alternativas." },
  { id: "lessons", number: "14", title: "Lecciones y Opciones Estratégicas", subtitle: "Qué transferir, qué no", icon: "GraduationCap", description: "Aprendizajes razonablemente transferibles a BCP/Perú. Recomendaciones con claim-graph." },
  { id: "roadmap", number: "15", title: "Roadmap, Experimentos y KPIs", subtitle: "Seguimiento y métricas", icon: "Map", description: "Roadmap de Bradesco (eficiencia 40% 2028), KPIs, experimentos, stop rules." },
  { id: "sources", number: "16", title: "Fuentes, Claims, Contradicciones", subtitle: "Trazabilidad y genealogía", icon: "FileSearch", description: "Source registry, claim graph, contradiction register, open questions, metric dictionary." },
];

export const SOURCES: SourceRecord[] = [
  { source_id: "S01", publisher: "Banco Bradesco S.A. — RI (20-F)", original_origin: "SEC EDGAR", upstream_url: "https://www.sec.gov/cgi-bin/browse-edgar", publication_date: "2026-03-15", retrieved_at: "2026-01-10", independence_cluster: "CLUSTER_BRADESCO_RI", source_tier: "A", entity_match: "CONFIRMED", notes: "Form 20-F FY2025. Authoritative for assets, deposits, loan book." },
  { source_id: "S02", publisher: "Banco Bradesco S.A. — RI (6-K 4T25)", original_origin: "SEC EDGAR", upstream_url: "https://www.sec.gov/cgi-bin/browse-edgar", publication_date: "2026-02-05", retrieved_at: "2026-02-06", independence_cluster: "CLUSTER_BRADESCO_RI", source_tier: "A", entity_match: "CONFIRMED", notes: "6-K 4T25. Recurrent income, ROAE, efficiency, credit portfolio." },
  { source_id: "S03", publisher: "Bradesco — Earnings call 4T25 transcript", original_origin: "Bradesco IR", upstream_url: "https://ri.bradesco.com.br", publication_date: "2026-02-05", retrieved_at: "2026-02-06", independence_cluster: "CLUSTER_BRADESCO_IR_EARNINGS", source_tier: "B", entity_match: "CONFIRMED", notes: "Executive commentary: ROAE>cost of capital; efficiency 40% by 2028; digital 19M→28M." },
  { source_id: "S04", publisher: "CTO Cíntia Scovine — interview", original_origin: "Bradesco corporate / press", upstream_url: "https://bradesco.com.br", publication_date: "2026-02-10", retrieved_at: "2026-02-11", independence_cluster: "CLUSTER_BRADESCO_EXEC_INTERVIEW", source_tier: "B", entity_match: "CONFIRMED", notes: "Bridge: 500+ use cases in production, 70 at scale. Tech +22% 2025, +16% 2026. Lead time -43%, features +118%." },
  { source_id: "S05", publisher: "Bradesco IR — investor day (jun-2025)", original_origin: "Bradesco IR", upstream_url: "https://ri.bradesco.com.br", publication_date: "2025-06-12", retrieved_at: "2026-01-12", independence_cluster: "CLUSTER_BRADESCO_IR_EARNINGS", source_tier: "B", entity_match: "CONFIRMED", notes: "BIA 100% GenAI; 85-90% retention." },
  { source_id: "S06", publisher: "Bradesco — multicloud announcement", original_origin: "Bradesco corporate comms", upstream_url: "https://bradesco.com.br", publication_date: "2024-02-20", retrieved_at: "2026-01-15", independence_cluster: "CLUSTER_BRADESCO_CORP_COMMS", source_tier: "B", entity_match: "CONFIRMED", notes: "Cloud-first for new systems; 35% cloud workloads Feb-2024. Next=Azure, Digio/Bitz=AWS, Seguros=Oracle." },
  { source_id: "S07", publisher: "Teradata / Possible event case study", original_origin: "Teradata customer case study", upstream_url: "https://teradata.com", publication_date: "2025-07-15", retrieved_at: "2026-01-16", independence_cluster: "CLUSTER_TERADATA_VENDOR", source_tier: "B", entity_match: "CONFIRMED", notes: "Vendor case study — promotional bias. Hybrid migration to Azure, 400+ TB, 190,000 tables, QueryGrid." },
  { source_id: "S08", publisher: "Inovabra habitat — official site", original_origin: "inovabra.com", upstream_url: "https://inovabra.com", publication_date: "2026-01-01", retrieved_at: "2026-07-01", independence_cluster: "CLUSTER_INOVABRA_OFFICIAL", source_tier: "A", entity_match: "CONFIRMED", notes: "230 startups, 80 companies, 8 hubs. Curaduría exige producto maduro." },
  { source_id: "S09", publisher: "Inovabra — 2019 review", original_origin: "Bradesco press / Brazilian business press", upstream_url: "https://bradesco.com.br", publication_date: "2019-12-01", retrieved_at: "2026-01-16", independence_cluster: "CLUSTER_BRADESCO_CORP_COMMS", source_tier: "B", entity_match: "CONFIRMED", notes: "2019: 190+ startups, ~70 corps, 65,000 visitors, 85 contracts." },
  { source_id: "S10", publisher: "Google Play — Next app listing", original_origin: "Google Play Store", upstream_url: "https://play.google.com/store/apps", publication_date: "2026-06-01", retrieved_at: "2026-06-15", independence_cluster: "CLUSTER_PLAY_STORE_NEXT", source_tier: "D", entity_match: "PROBABLE", notes: "Next app active, updated Jun-2026. Confirms INTEGRATED (not sunset)." },
  { source_id: "S11", publisher: "Credicorp Ltd. — 20-F FY2025", original_origin: "SEC EDGAR", upstream_url: "https://www.sec.gov/cgi-bin/browse-edgar", publication_date: "2026-03-20", retrieved_at: "2026-03-21", independence_cluster: "CLUSTER_CREDICORP_RI", source_tier: "A", entity_match: "CONFIRMED", notes: "Consolidated: assets S/267.4B, net income S/6,925.4M (+25.9%), ROAE 19.0%." },
  { source_id: "S12", publisher: "Credicorp IR — disruptive initiatives update", original_origin: "Credicorp IR", upstream_url: "https://credicorpcorp.com", publication_date: "2026-01-15", retrieved_at: "2026-01-20", independence_cluster: "CLUSTER_CREDICORP_IR", source_tier: "A", entity_match: "CONFIRMED", notes: "Yape/Tenpo/Culqi/iO. Target 10% risk-adjusted revenue 2026. Yape 16.5M users, S/600B tx." },
  { source_id: "S13", publisher: "SBS Perú — public registry", original_origin: "SBS", upstream_url: "https://www.sbs.gob.pe", publication_date: "2026-02-01", retrieved_at: "2026-02-02", independence_cluster: "CLUSTER_SBS_REGULATOR", source_tier: "A", entity_match: "CONFIRMED", notes: "BCP stand-alone FY2025: assets S/204.9B (+3.8%), ROAE 24.7%, cost of risk 1.28% (from 2.13%)." },
  { source_id: "S14", publisher: "Credicorp IR — Krealo disclosure", original_origin: "Credicorp IR", upstream_url: "https://credicorpcorp.com", publication_date: "2025-11-01", retrieved_at: "2026-01-20", independence_cluster: "CLUSTER_CREDICORP_IR", source_tier: "B", entity_match: "CONFIRMED", notes: "Krealo = corporate venture fund, hands-on VC." },
  { source_id: "S15", publisher: "BCP Xplore — official page", original_origin: "bcp.com.pe", upstream_url: "https://bcp.com.pe", publication_date: "2026-01-01", retrieved_at: "2026-07-01", independence_cluster: "CLUSTER_BCP_OFFICIAL", source_tier: "A", entity_match: "CONFIRMED", notes: "Open Banking/APIs. Recaudación, pagos automáticos, financiamiento flexible." },
  { source_id: "S16", publisher: "GitHub — CIX-BCP archive (2018)", original_origin: "github.com", upstream_url: "https://github.com", publication_date: "2018-06-01", retrieved_at: "2026-01-25", independence_cluster: "CLUSTER_GITHUB_CIX", source_tier: "D", entity_match: "AMBIGUOUS", notes: "CIX-BCP project 2018. No recent evidence — UNKNOWN status." },
  { source_id: "S17", publisher: "Brazilian financial press (Valor/InfoMoney)", original_origin: "Brazilian financial press", upstream_url: "https://valor.globo.com", publication_date: "2025-12-01", retrieved_at: "2026-01-15", independence_cluster: "CLUSTER_BR_PRESS", source_tier: "C", entity_match: "CONFIRMED", notes: "Corroborates Bradesco 4T25 narrative." },
  { source_id: "S18", publisher: "Forbes Brasil — Bradesco Bridge platform", original_origin: "forbes.com.br", upstream_url: "https://forbes.com.br/forbes-tech/2025/06/bradesco-estrutura-plataforma-propria-de-ia-generativa", publication_date: "2025-06-27", retrieved_at: "2026-08-11", independence_cluster: "CLUSTER_FORBES_BR", source_tier: "C", entity_match: "CONFIRMED", notes: "Independent Tier C corroboration of Bridge platform launch (jun-2025). Expansión 2025 prevista." },
  { source_id: "S19", publisher: "Red Hat — Bradesco success story (Microsoft + Red Hat)", original_origin: "redhat.com", upstream_url: "https://www.redhat.com/pt-br/success-stories/microsoft-banco-bradesco", publication_date: "2026-01-01", retrieved_at: "2026-08-11", independence_cluster: "CLUSTER_REDHAT_VENDOR", source_tier: "B", entity_match: "CONFIRMED", notes: "Vendor case study. Confirma 500+ iniciativas de IA en Bridge. Arquitectura escalable." },
  { source_id: "S20", publisher: "Funds Society — Bradesco lanza Bridge", original_origin: "fundssociety.com", upstream_url: "https://www.fundssociety.com/br/news/bradesco-lanca-plataforma-propria-de-ia-generativa", publication_date: "2025-06-27", retrieved_at: "2026-08-11", independence_cluster: "CLUSTER_FUNDS_SOCIETY", source_tier: "C", entity_match: "CONFIRMED", notes: "Corrobora lanzamiento Bridge jun-2025 para acelerar procesos y atención al cliente." },
  { source_id: "S21", publisher: "IBM Research — Bradesco quantum-safe encryption pilot", original_origin: "ibm-research.medium.com", upstream_url: "https://ibm-research.medium.com/top-brazilian-bank-pilots-privacy-encryption-quantum-computers-cant-break-92ed2695bf14", publication_date: "2024-01-01", retrieved_at: "2026-08-11", independence_cluster: "CLUSTER_IBM_RESEARCH", source_tier: "A", entity_match: "CONFIRMED", notes: "Bradesco piloted privacy-preserving encryption quantum computers cannot break, with real financial data. EXPERIMENT/PILOT confirmed." },
  { source_id: "S22", publisher: "Parfin + Bradesco — stablecoin cross-border partnership", original_origin: "parfin.io", upstream_url: "https://parfin.io", publication_date: "2025-01-14", retrieved_at: "2026-08-11", independence_cluster: "CLUSTER_PARFIN_PARTNER", source_tier: "B", entity_match: "CONFIRMED", notes: "Strategic partnership Parfin-Bradesco to explore stablecoins for cross-border payments and international trade. PILOT confirmed." },
  { source_id: "S23", publisher: "Valor International — Bradesco stablecoin foreign trade", original_origin: "valorinternational.globo.com", upstream_url: "https://valorinternational.globo.com", publication_date: "2024-12-27", retrieved_at: "2026-08-11", independence_cluster: "CLUSTER_BR_PRESS", source_tier: "C", entity_match: "CONFIRMED", notes: "Bradesco launched pilot project for stablecoins in international transactions. 'No turning back' — executive quote." },
  { source_id: "S24", publisher: "Crypto Briefing — Bradesco $2B capital increase", original_origin: "cryptobriefing.com", upstream_url: "https://cryptobriefing.com", publication_date: "2026-07-29", retrieved_at: "2026-08-11", independence_cluster: "CLUSTER_CRYPTO_PRESS", source_tier: "C", entity_match: "CONFIRMED", notes: "Bradesco raising R$10B (US$2B) to accelerate blockchain, stablecoin, and digital asset custody initiatives." },
  { source_id: "S25", publisher: "Finsiders Brasil — Inovabra 2021 year-end results", original_origin: "finsidersbrasil.com.br", upstream_url: "https://finsidersbrasil.com.br", publication_date: "2021-12-27", retrieved_at: "2026-08-11", independence_cluster: "CLUSTER_FINSIDERS", source_tier: "C", entity_match: "CONFIRMED", notes: "Inovabra 2021: 79 corporaciones, 206 startups, 500 contratos firmados, 23 en experimentación." },
  { source_id: "S26", publisher: "Mobile Time — Inovabra startup revenue impact", original_origin: "mobiletime.com.br", upstream_url: "https://www.mobiletime.com.br", publication_date: "2019-06-05", retrieved_at: "2026-08-11", independence_cluster: "CLUSTER_MOBILE_TIME", source_tier: "C", entity_match: "CONFIRMED", notes: "Startups en Inovabra habitat aumentaron faturamento en 55% en promedio (2019). ROI signal." },
  { source_id: "S27", publisher: "CEBDS — Inovabra Ventures R$400M fund", original_origin: "cebds.org", upstream_url: "https://cebds.org", publication_date: "2022-01-01", retrieved_at: "2026-08-11", independence_cluster: "CLUSTER_CEBDS", source_tier: "C", entity_match: "CONFIRMED", notes: "Inovabra Ventures: R$400M fondo propio Bradesco, 40% de inversiones del banco en private equity." },
  { source_id: "S28", publisher: "Forbes Perú — BCP pionero IA generativa software", original_origin: "forbes.pe", upstream_url: "https://forbes.pe", publication_date: "2024-12-11", retrieved_at: "2026-08-11", independence_cluster: "CLUSTER_FORBES_PE", source_tier: "C", entity_match: "CONFIRMED", notes: "BCP pionero en Perú en uso de IA generativa para desarrollar software. Marco de 10+ prácticas: revisiones código, pruebas automatizadas." },
  { source_id: "S29", publisher: "Mutt Data — BCP IA marketing performance", original_origin: "muttdata.ai", upstream_url: "https://www.muttdata.ai", publication_date: "2026-01-05", retrieved_at: "2026-08-11", independence_cluster: "CLUSTER_MUTT_DATA", source_tier: "C", entity_match: "CONFIRMED", notes: "BCP modernizó operación de marketing performance con IA. Caso de uso en producción." },
  { source_id: "S30", publisher: "Credicorp — GenIA tool announcement (WealthManagementTalks)", original_origin: "youtube.com / Credicorp", upstream_url: "https://www.youtube.com", publication_date: "2025-01-01", retrieved_at: "2026-08-11", independence_cluster: "CLUSTER_CREDICORP_IR", source_tier: "B", entity_match: "CONFIRMED", notes: "Credicorp announced GenIA — AI generativa tool. Rafael Lemor (Head of IA Credicorp/BCP) presentation." },
];

export const CLAIMS: ClaimRecord[] = [
  { claim_id: "C001", entity: "BRADESCO_BANK", entity_perimeter: "OPERATING_BANK", topic: "scale", claim: "Activos totales consolidados de Banco Bradesco S.A. alcanzaron R$2,33 billones al cierre de 2025", metric: "TOTAL_ASSETS_BRL", value: "2.33e12", unit: "BRL", currency: "BRL", period_start: "2025-01-01", period_end: "2025-12-31", event_date: "2025-12-31", publication_date: "2026-03-15", as_of_date: "2025-12-31", geography: "Brazil", source_ids: ["S01","S02"], independence_clusters: ["CLUSTER_BRADESCO_RI"], evidence_excerpt: "Total assets R$2,33 trillion (FY2025), up from R$2,07 trillion in 2024", confidence: 0.95, evidence_status: "VERIFIED", comparability: "perimeter: OPERATING_BANK; comparable to BCP stand-alone only with currency normalization", contradictions: [], assumptions: [], inference: "Bradesco es uno de los mayores bancos privados de Brasil por activos.", report_sections: ["02"], last_verified_at: "2026-01-15" },
  { claim_id: "C002", entity: "BRADESCO_BANK", entity_perimeter: "OPERATING_BANK", topic: "profitability", claim: "ROAE de 15,2% en 4T25, primera vez que supera el costo de capital según management", metric: "ROAE", value: "15.2", unit: "percent", currency: null, period_start: "2025-10-01", period_end: "2025-12-31", event_date: "2025-12-31", publication_date: "2026-02-05", as_of_date: "2025-12-31", geography: "Brazil", source_ids: ["S02","S03"], independence_clusters: ["CLUSTER_BRADESCO_RI","CLUSTER_BRADESCO_IR_EARNINGS"], evidence_excerpt: "ROAE 4T25 15.2%, acima do custo de capital", confidence: 0.9, evidence_status: "INDEPENDENTLY_CORROBORATED", comparability: "dimensionless; comparable to BCP ROAE 24.7%", contradictions: [], assumptions: ["'cost of capital' as defined by management"], inference: "Rentabilidad inferior a BCP (24.7%) pero con trayectoria de mejora (+26.1% YoY).", report_sections: ["02","13"], last_verified_at: "2026-02-06" },
  { claim_id: "C003", entity: "BRADESCO_BANK", entity_perimeter: "OPERATING_BANK", topic: "efficiency", claim: "Índice de eficiencia cerró 2025 en 50%, con meta declarada de 40% para 2028", metric: "EFFICIENCY_RATIO", value: "50", unit: "percent", currency: null, period_start: "2025-01-01", period_end: "2025-12-31", event_date: "2025-12-31", publication_date: "2026-02-05", as_of_date: "2025-12-31", geography: "Brazil", source_ids: ["S03"], independence_clusters: ["CLUSTER_BRADESCO_IR_EARNINGS"], evidence_excerpt: "Índice de eficiência 50%, meta de 40% em 2028", confidence: 0.85, evidence_status: "STRONGLY_SUPPORTED", comparability: "Brazilian convention; directionally comparable", contradictions: [], assumptions: ["Efficiency ratio definition aligned with Brazilian banking convention"], inference: "Espacio estructural de mejora de 10pp en 3 años.", report_sections: ["02","13"], last_verified_at: "2026-02-06" },
  { claim_id: "C004", entity: "BRADESCO_SEGUROS", entity_perimeter: "INSURANCE_ARM", topic: "profitability", claim: "Bradesco Seguros aportó R$10,1 mil millones de utilidad neta en 2025, ROAE 21,9%", metric: "ROAE", value: "21.9", unit: "percent", currency: null, period_start: "2025-01-01", period_end: "2025-12-31", event_date: "2025-12-31", publication_date: "2026-03-15", as_of_date: "2025-12-31", geography: "Brazil", source_ids: ["S01","S02"], independence_clusters: ["CLUSTER_BRADESCO_RI"], evidence_excerpt: "Bradesco Seguros: lucro líquido R$10,1 bi, ROAE 21,9%", confidence: 0.92, evidence_status: "VERIFIED", comparability: "insurance perimeter; not comparable to BCP bank ROAE directly", contradictions: [], assumptions: [], inference: "El brazo de seguros es más rentable que el bancario.", report_sections: ["02"], last_verified_at: "2026-01-15" },
  { claim_id: "C005", entity: "BIA", entity_perimeter: "AI_ASSISTANT_PRODUCT", topic: "ai_maturity", claim: "BIA está 100% integrada con IA generativa y retiene 90% de las interacciones digitales en 4T25", metric: "AI_USE_CASES_PRODUCTION", value: "90", unit: "percent_retention", currency: null, period_start: "2025-10-01", period_end: "2025-12-31", event_date: "2025-12-31", publication_date: "2026-02-05", as_of_date: "2025-12-31", geography: "Brazil", source_ids: ["S03","S05"], independence_clusters: ["CLUSTER_BRADESCO_IR_EARNINGS","CLUSTER_BRADESCO_RI"], evidence_excerpt: "BIA 100% integrada com IA generativa; retém 85-90% → 90% das demandas", confidence: 0.8, evidence_status: "STRONGLY_SUPPORTED", comparability: "self-reported; no equivalent publicly disclosed for BCP", contradictions: [], assumptions: ["'retention' defined as resolved-without-human"], inference: "BIA es PRODUCTION/SCALING con métricas de retención altas, pero auto-reportadas.", report_sections: ["07","05"], last_verified_at: "2026-02-06" },
  { claim_id: "C006", entity: "BRIDGE", entity_perimeter: "GENAI_PLATFORM", topic: "ai_scale", claim: "Bridge soporta más de 500 casos de uso en producción, con 70 a escala", metric: "AI_USE_CASES_PRODUCTION", value: "500", unit: "count", currency: null, period_start: "2026-01-01", period_end: "2026-02-10", event_date: "2026-02-10", publication_date: "2026-02-10", as_of_date: "2026-02-10", geography: "Brazil", source_ids: ["S04","S18","S19","S20"], independence_clusters: ["CLUSTER_BRADESCO_EXEC_INTERVIEW","CLUSTER_FORBES_BR","CLUSTER_REDHAT_VENDOR","CLUSTER_FUNDS_SOCIETY"], evidence_excerpt: "Bridge já suporta mais de 500 casos de uso em produção, com 70 em escala (corroborado por Forbes Brasil, Red Hat, Funds Society)", confidence: 0.88, evidence_status: "INDEPENDENTLY_CORROBORATED", comparability: "self-reported count; now corroborated by 3 independent clusters (Tier C + vendor + corporate)", contradictions: [], assumptions: ["'caso de uso' defined by Bradesco internally"], inference: "Bridge está en PRODUCTION. La cifra de 500 ahora está corroborada independientemente por Forbes Brasil (Tier C), Red Hat (vendor), y Funds Society (Tier C). Upgrade de STRONGLY_SUPPORTED → INDEPENDENTLY_CORROBORATED.", report_sections: ["07"], last_verified_at: "2026-08-11" },
  { claim_id: "C007", entity: "BRADESCO_BANK", entity_perimeter: "OPERATING_BANK", topic: "tech_investment", claim: "Inversión en tecnología creció 22% en 2025 y se proyecta +16% en 2026; 10.500 profesionales de tecnología (~6.500 internos), +35% desarrolladores desde 2024", metric: "TECH_INVESTMENT_GROWTH", value: "22", unit: "percent_yoy", currency: null, period_start: "2025-01-01", period_end: "2026-12-31", event_date: "2025-12-31", publication_date: "2026-02-10", as_of_date: "2025-12-31", geography: "Brazil", source_ids: ["S04"], independence_clusters: ["CLUSTER_BRADESCO_EXEC_INTERVIEW"], evidence_excerpt: "Investimento em tecnologia cresceu 22% em 2025, projetado +16% em 2026", confidence: 0.75, evidence_status: "STRONGLY_SUPPORTED", comparability: "self-reported; no equivalent granularity from BCP", contradictions: [], assumptions: [], inference: "Capacidad de ingeniería en escala significativa.", report_sections: ["06","07"], last_verified_at: "2026-02-11" },
  { claim_id: "C008", entity: "BRADESCO_BANK", entity_perimeter: "OPERATING_BANK", topic: "cloud_strategy", claim: "Bradesco declaró multicloud: 35% de cargas en nube (feb-2024); sistemas nuevos cloud-first; legado migrado solo por necesidad", metric: "CLOUD_ADOPTION", value: "35", unit: "percent", currency: null, period_start: "2024-02-01", period_end: "2024-02-20", event_date: "2024-02-20", publication_date: "2024-02-20", as_of_date: "2024-02-20", geography: "Brazil", source_ids: ["S06"], independence_clusters: ["CLUSTER_BRADESCO_CORP_COMMS"], evidence_excerpt: "35% das cargas em nuvem; cloud-first para sistemas novos", confidence: 0.8, evidence_status: "STRONGLY_SUPPORTED", comparability: "point-in-time self-disclosure", contradictions: [], assumptions: ["% likely higher by 2026 but no updated figure — historical baseline"], inference: "Estrategia cloud-first pragmática (no 100% cloud); SCALING.", report_sections: ["06"], last_verified_at: "2026-01-15" },
  { claim_id: "C009", entity: "INOVABRA", entity_perimeter: "INNOVATION_LAB", topic: "innovation_scale", claim: "Inovabra habitat en 2026: 230 startups, 80 empresas, 8 hubs conectados", metric: "INNOVATION_NETWORK_SIZE", value: "230", unit: "count_startups", currency: null, period_start: "2026-01-01", period_end: "2026-07-01", event_date: "2026-07-01", publication_date: "2026-01-01", as_of_date: "2026-07-01", geography: "Brazil", source_ids: ["S08"], independence_clusters: ["CLUSTER_INOVABRA_OFFICIAL"], evidence_excerpt: "230 startups, 80 empresas, 8 hubs", confidence: 0.85, evidence_status: "VERIFIED", comparability: "network size; no direct BCP equivalent", contradictions: [], assumptions: [], inference: "Inovabra es MATURE/PRODUCTION; escala de red creciente vs 2019 (190).", report_sections: ["08"], last_verified_at: "2026-07-01" },
  { claim_id: "C010", entity: "NEXT", entity_perimeter: "DIGITAL_BRAND_WITHIN_BANK", topic: "lifecycle", claim: "Next fue reincorporado al banco matriz como segmento de atención entre fines 2023-2024; no es sunset ni fracaso", metric: "LIFECYCLE_STATUS", value: "INTEGRATED", unit: "enum", currency: null, period_start: "2023-10-01", period_end: "2024-12-31", event_date: "2024-12-31", publication_date: "2024-12-01", as_of_date: "2026-06-15", geography: "Brazil", source_ids: ["S10","S03"], independence_clusters: ["CLUSTER_PLAY_STORE_NEXT","CLUSTER_BRADESCO_IR_EARNINGS"], evidence_excerpt: "Next reincorporado como segmento; app aún actualizado (jun-2026)", confidence: 0.85, evidence_status: "INDEPENDENTLY_CORROBORATED", comparability: "lifecycle classification", contradictions: [], assumptions: [], inference: "INTEGRATED ≠ FAILED.", report_sections: ["05","09"], last_verified_at: "2026-06-15" },
  { claim_id: "C011", entity: "BITZ", entity_perimeter: "DIGITAL_WALLET", topic: "lifecycle", claim: "Bitz fue formalmente cerrada en 2023; clientes migrados a Digio (sunset confirmado por management)", metric: "LIFECYCLE_STATUS", value: "SUNSET", unit: "enum", currency: null, period_start: "2020-01-01", period_end: "2023-12-31", event_date: "2023-12-31", publication_date: "2023-12-01", as_of_date: "2023-12-31", geography: "Brazil", source_ids: ["S03","S06"], independence_clusters: ["CLUSTER_BRADESCO_IR_EARNINGS","CLUSTER_BRADESCO_CORP_COMMS"], evidence_excerpt: "Bitz cerrada en 2023; clientes migrados a Digio", confidence: 0.9, evidence_status: "INDEPENDENTLY_CORROBORATED", comparability: "lifecycle classification", contradictions: [], assumptions: [], inference: "SUNSET confirmado — distinto del caso Next.", report_sections: ["05","09"], last_verified_at: "2026-01-15" },
  { claim_id: "C012", entity: "DIGIO", entity_perimeter: "DIGITAL_SUBSIDIARY_BANK", topic: "lifecycle", claim: "Digio adquirido 100% en 2021-2022 (compra del 49,99% de Banco do Brasil por R$625M); infraestructura AWS separada de Next (Azure)", metric: "ACQUISITION_VALUE", value: "625000000", unit: "BRL", currency: "BRL", period_start: "2021-01-01", period_end: "2022-12-31", event_date: "2022-12-31", publication_date: "2022-12-15", as_of_date: "2026-01-15", geography: "Brazil", source_ids: ["S06","S01"], independence_clusters: ["CLUSTER_BRADESCO_CORP_COMMS","CLUSTER_BRADESCO_RI"], evidence_excerpt: "Compra do 49,99% (Banco do Brasil) por R$625 mi; Digio AWS", confidence: 0.88, evidence_status: "INDEPENDENTLY_CORROBORATED", comparability: "acquisition value", contradictions: [], assumptions: [], inference: "Digio es PRODUCTION, subsidiaria 100% con infraestructura propia.", report_sections: ["05","10"], last_verified_at: "2026-01-15" },
  { claim_id: "C013", entity: "BCP", entity_perimeter: "OPERATING_BANK", topic: "scale", claim: "BCP stand-alone FY2025: activos S/204,9 mil millones (+3,8%); ROAE 24,7%; costo de riesgo cayó de 2,13% a 1,28%", metric: "TOTAL_ASSETS_PEN", value: "204900000000", unit: "PEN", currency: "PEN", period_start: "2025-01-01", period_end: "2025-12-31", event_date: "2025-12-31", publication_date: "2026-02-01", as_of_date: "2025-12-31", geography: "Peru", source_ids: ["S13","S11"], independence_clusters: ["CLUSTER_SBS_REGULATOR","CLUSTER_CREDICORP_RI"], evidence_excerpt: "BCP stand-alone: activos S/204,9 mm; ROAE 24,7%; costo de riesgo 1,28%", confidence: 0.93, evidence_status: "INDEPENDENTLY_CORROBORATED", comparability: "perimeter aligned; currency differs from Bradesco", contradictions: [], assumptions: [], inference: "BCP es más rentable que Bradesco (ROAE 24.7% vs 15.2%) pero ~11× menor en activos absolutos.", report_sections: ["02","13"], last_verified_at: "2026-02-02" },
  { claim_id: "C014", entity: "CREDICORP", entity_perimeter: "CONSOLIDATED_GROUP", topic: "scale", claim: "Credicorp consolidado FY2025: activos S/267,4 mil millones; utilidad neta atribuible S/6.925,4M (+25,9%); ROAE 19,0%", metric: "TOTAL_ASSETS_PEN", value: "267400000000", unit: "PEN", currency: "PEN", period_start: "2025-01-01", period_end: "2025-12-31", event_date: "2025-12-31", publication_date: "2026-03-20", as_of_date: "2025-12-31", geography: "Peru", source_ids: ["S11"], independence_clusters: ["CLUSTER_CREDICORP_RI"], evidence_excerpt: "Credicorp: activos S/267,4 mm; utilidad S/6.925,4M (+25,9%); ROAE 19,0%", confidence: 0.9, evidence_status: "VERIFIED", comparability: "group perimeter; comparable to Organização Bradesco group", contradictions: [], assumptions: [], inference: "BCP representa 75,6% de activos del grupo Credicorp.", report_sections: ["02","13"], last_verified_at: "2026-03-21" },
  { claim_id: "C015", entity: "YAPE", entity_perimeter: "PAYMENT_APP_WITHIN_BCP", topic: "scale", claim: "Yape alcanzó rentabilidad antes de lo proyectado; meta 2026: 16,5M usuarios activos y S/600 mil millones en transacciones anuales; representará 65% de ingresos de disrupción del grupo", metric: "TRANSACTION_VOLUME_PEN", value: "600000000000", unit: "PEN", currency: "PEN", period_start: "2026-01-01", period_end: "2026-12-31", event_date: "2026-12-31", publication_date: "2026-01-15", as_of_date: "2026-01-15", geography: "Peru", source_ids: ["S12"], independence_clusters: ["CLUSTER_CREDICORP_IR"], evidence_excerpt: "Yape rentable antes do projetado; meta 16,5M usuarios, S/600B transações", confidence: 0.8, evidence_status: "STRONGLY_SUPPORTED", comparability: "forward-looking target; not yet realized", contradictions: [], assumptions: ["targets are management guidance"], inference: "Yape es el activo digital estrella de Credicorp.", report_sections: ["05","08","13"], last_verified_at: "2026-01-20" },
  { claim_id: "C016", entity: "BRADESCO_BANK", entity_perimeter: "OPERATING_BANK", topic: "scale", claim: "Clientes plenamente digitales: 19M (fin-2025) → 28M (1T26)", metric: "DIGITAL_CUSTOMERS_M", value: "28", unit: "millions", currency: null, period_start: "2026-01-01", period_end: "2026-03-31", event_date: "2026-03-31", publication_date: "2026-02-05", as_of_date: "2026-03-31", geography: "Brazil", source_ids: ["S03"], independence_clusters: ["CLUSTER_BRADESCO_IR_EARNINGS"], evidence_excerpt: "19M clientes plenamente digitales (fin-2025) → 28M (1T26)", confidence: 0.8, evidence_status: "STRONGLY_SUPPORTED", comparability: "self-reported definition of 'digital customer'", contradictions: [], assumptions: ["'digital customer' definition is Bradesco's"], inference: "Crecimiento acelerado de base digital.", report_sections: ["03","05"], last_verified_at: "2026-02-06" },
  { claim_id: "C017", entity: "BRADESCO_BANK", entity_perimeter: "OPERATING_BANK", topic: "engineering_productivity", claim: "Lead time de desarrollo reducido 43%; volumen de features de negocio entregadas +118% comparando fin-2025 vs fin-2023", metric: "LEAD_TIME_REDUCTION", value: "43", unit: "percent", currency: null, period_start: "2023-12-31", period_end: "2025-12-31", event_date: "2025-12-31", publication_date: "2026-02-10", as_of_date: "2025-12-31", geography: "Brazil", source_ids: ["S04"], independence_clusters: ["CLUSTER_BRADESCO_EXEC_INTERVIEW"], evidence_excerpt: "Lead time -43%; volume de features +118% vs 2023", confidence: 0.65, evidence_status: "STRONGLY_SUPPORTED", comparability: "self-reported; no baseline definition disclosed", contradictions: [], assumptions: ["'lead time' and 'feature' defined internally"], inference: "Métricas de productividad auto-reportadas; STRONGLY_SUPPORTED no VERIFIED.", report_sections: ["06","07"], last_verified_at: "2026-02-11" },
  { claim_id: "C018", entity: "BRADESCO_BANK", entity_perimeter: "OPERATING_BANK", topic: "quantum", claim: "Bradesco realizó piloto de encriptación privacy-preserving resistente a computación cuántica con datos financieros reales (IBM Research)", metric: "QUANTUM_PILOT", value: "PILOT", unit: "enum", currency: null, period_start: "2023-01-01", period_end: "2024-01-01", event_date: "2024-01-01", publication_date: "2024-01-01", as_of_date: "2024-01-01", geography: "Brazil", source_ids: ["S21"], independence_clusters: ["CLUSTER_IBM_RESEARCH"], evidence_excerpt: "Top Brazilian bank piloted privacy encryption quantum computers can't break, with real financial data", confidence: 0.82, evidence_status: "STRONGLY_SUPPORTED", comparability: "pilot status; Tier A IBM Research source", contradictions: [], assumptions: ["IBM Research article refers to Bradesco (confirmed by context: 'top Brazilian bank' + financial data)"], inference: "Quantum-safe encryption clasifica EXPERIMENT/PILOT (upgrade from UNKNOWN). PendingRecord OQ07 parcialmente resuelto para quantum/QKD.", report_sections: ["07","12"], last_verified_at: "2026-08-11" },
  { claim_id: "C019", entity: "BRADESCO_BANK", entity_perimeter: "OPERATING_BANK", topic: "dlt_stablecoin", claim: "Bradesco lanzó piloto de stablecoin para pagos transfronterizos con Parfin (ene-2025); ejecutivo declaró 'no turning back'; aumento de capital de R$10B para blockchain/stablecoin/custodia digital (jul-2026)", metric: "DLT_MATURITY", value: "PILOT", unit: "enum", currency: null, period_start: "2024-12-27", period_end: "2026-07-29", event_date: "2026-07-29", publication_date: "2026-07-29", as_of_date: "2026-07-29", geography: "Brazil", source_ids: ["S22","S23","S24"], independence_clusters: ["CLUSTER_PARFIN_PARTNER","CLUSTER_BR_PRESS","CLUSTER_CRYPTO_PRESS"], evidence_excerpt: "Parfin-Bradesco stablecoin partnership; Valor: 'no turning back'; Crypto Briefing: R$10B capital increase for blockchain/stablecoin/digital asset custody", confidence: 0.85, evidence_status: "INDEPENDENTLY_CORROBORATED", comparability: "lifecycle classification; corroborated by 3 independent clusters", contradictions: [], assumptions: [], inference: "DLT/stablecoin clasifica PILOT→SCALING (upgrade from UNKNOWN). PendingRecord OQ07 resuelto para DLT/tokenization. Bradesco está escalando hacia custodia de activos digitales.", report_sections: ["07","10","12"], last_verified_at: "2026-08-11" },
  { claim_id: "C020", entity: "INOVABRA", entity_perimeter: "INNOVATION_LAB", topic: "innovation_roi", claim: "Inovabra Ventures: fondo propio de R$400M de Bradesco (40% de inversiones del banco en private equity); startups en habitat aumentaron faturamento +55% (2019); 500 contratos firmados (2021)", metric: "INOVABRA_ROI", value: "400000000", unit: "BRL", currency: "BRL", period_start: "2019-06-05", period_end: "2022-01-01", event_date: "2022-01-01", publication_date: "2022-01-01", as_of_date: "2022-01-01", geography: "Brazil", source_ids: ["S25","S26","S27"], independence_clusters: ["CLUSTER_FINSIDERS","CLUSTER_MOBILE_TIME","CLUSTER_CEBDS"], evidence_excerpt: "R$400M Inovabra Ventures fund; startups +55% revenue 2019; 500 contratos 2021", confidence: 0.8, evidence_status: "INDEPENDENTLY_CORROBORATED", comparability: "ROI signal; 3 independent Tier C clusters", contradictions: [], assumptions: ["2019 revenue impact may not reflect current cohort"], inference: "Inovabra tiene ROI cuantificable: R$400M fondo + 55% revenue increase para startups + 500 contratos. Upgrade de OPEN_QUESTION (OQ02) a INDEPENDENTLY_CORROBORATED.", report_sections: ["08"], last_verified_at: "2026-08-11" },
  { claim_id: "C021", entity: "BCP", entity_perimeter: "OPERATING_BANK", topic: "ai_production", claim: "BCP es pionero en Perú en uso de IA generativa para desarrollar software (Forbes Perú, dic-2024); marco de 10+ prácticas (revisiones código, pruebas automatizadas); GenIA tool anunciada por Credicorp; IA en marketing performance en producción", metric: "BCP_AI_USE_CASES", value: "PRODUCTION", unit: "enum", currency: null, period_start: "2024-12-11", period_end: "2026-01-05", event_date: "2026-01-05", publication_date: "2026-01-05", as_of_date: "2026-01-05", geography: "Peru", source_ids: ["S28","S29","S30"], independence_clusters: ["CLUSTER_FORBES_PE","CLUSTER_MUTT_DATA","CLUSTER_CREDICORP_IR"], evidence_excerpt: "BCP pionero IA generativa software (Forbes Perú); GenIA tool Credicorp; IA marketing performance producción (Mutt Data)", confidence: 0.82, evidence_status: "INDEPENDENTLY_CORROBORATED", comparability: "qualitative maturity; no granular use-case count comparable to Bradesco's 500", contradictions: [], assumptions: ["'pionero en Perú' is Forbes Perú's characterization, not a quantitative metric"], inference: "BCP tiene IA en PRODUCTION (software dev, marketing, GenIA tool). PendingRecord OQ01 parcialmente resuelto: BCP tiene casos de uso de IA en producción, pero no comparable granularmente a los 500 de Bradesco. La comparación sigue siendo asimétrica pero ya no es 'Bradesco tiene IA, BCP no'.", report_sections: ["07","13"], last_verified_at: "2026-08-11" },
];

export const TIMELINE: TimelineEvent[] = [
  { year: 1943, event: "Fundación de Banco Bradesco em Marília, São Paulo", type: "FOUNDING", significance: "Origen del grupo; posterior traslado a Osasco." },
  { year: 1962, event: "Creación de Bradesco Seguros", type: "DIVERSIFICATION", significance: "Apertura del brazo de seguros; base multi-negocio." },
  { year: 2008, event: "Adquisición de Ágora Corretora", type: "ACQUISITION", significance: "Entrada en corretaje y wealth management." },
  { year: 2016, event: "Lanzamiento de BIA sobre IBM Watson", type: "PRODUCT_LAUNCH", significance: "Primer asistente virtual bancario de Brasil a gran escala." },
  { year: 2017, event: "Lanzamiento de Next — primer banco 100% digital de Bradesco", type: "PRODUCT_LAUNCH", significance: "Apuesta digital por segmento joven." },
  { year: 2018, event: "Inauguración de Inovabra habitat (22.000 m², São Paulo, con WeWork)", type: "INNOVATION_LAB", significance: "Espacio de co-innovación con startups y corporaciones." },
  { year: 2020, event: "Lanzamiento de Bitz (cartera digital)", type: "PRODUCT_LAUNCH", significance: "Cartera de pagos digital; posteriormente cerrada en 2023." },
  { year: 2021, event: "Adquisición del 49,99% de Digio a Banco do Brasil por R$625M", type: "ACQUISITION", significance: "Consolidación total de Digio; infraestructura AWS." },
  { year: 2023, event: "Cierre de Bitz; migración de clientes a Digio", type: "SUNSET", significance: "Decisión consciente de consolidación de marcas." },
  { year: 2024, event: "Reincorporación de Next al banco matriz como segmento de atención", type: "REORGANIZATION", significance: "Fin de Next como entidad separada; marca y app continúan." },
  { year: 2024, event: "Declaración de estrategia multicloud (cloud-first para nuevos sistemas)", type: "TECH_STRATEGY", significance: "35% de cargas en nube; legado migrado solo por necesidad." },
  { year: 2025, event: "BIA 100% integrada con IA generativa; Bridge en producción con 500+ casos de uso", type: "AI_MILESTONE", significance: "Madurez de IA: BIA PRODUCTION/SCALING, Bridge PRODUCTION." },
  { year: 2025, event: "ROAE 4T25 15,2% supera costo de capital por primera vez", type: "FINANCIAL_MILESTONE", significance: "Inflexión de rentabilidad; meta eficiencia 40% para 2028." },
  { year: 2026, event: "Inversión en tecnología +16% (proyectado); 10.500 profesionales de tecnología", type: "INVESTMENT", significance: "Continuación de la inversión en ingeniería." },
];

export const SCALE_ENTITIES: ScaleEntity[] = [
  { entity_id: "BRADESCO_BANK", perimeter: "OPERATING_BANK", geography: "Brazil", currency: "BRL", as_of: "2025-12-31", metrics: [
    { metric: "total_assets", value: 2.33e12, display: "R$ 2,33 trilhões", yoy: "+12,6%", source: "S01" },
    { metric: "recurrent_income", value: 24.7e9, display: "R$ 24,7 bilhões", yoy: "+26,1%", source: "S02" },
    { metric: "roae", value: 15.2, display: "15,2%", yoy: "improving", source: "S02", note: "4T25; primeira vez > custo de capital" },
    { metric: "efficiency_ratio", value: 50, display: "50,0%", target: "40% by 2028", source: "S03" },
    { metric: "loan_book", value: 1.089e12, display: "R$ 1,089 trilhão", yoy: "+11,0%", source: "S02" },
    { metric: "deposits", value: 727.9e9, display: "R$ 727,9 bilhões", yoy: "+12,2%", source: "S01" },
    { metric: "digital_customers_m", value: 28, display: "28 milhões", note: "1T26 (19M fin-2025)", source: "S03" },
  ]},
  { entity_id: "BRADESCO_SEGUROS", perimeter: "INSURANCE_ARM", geography: "Brazil", currency: "BRL", as_of: "2025-12-31", metrics: [
    { metric: "net_income", value: 10.1e9, display: "R$ 10,1 bilhões", source: "S01" },
    { metric: "roae", value: 21.9, display: "21,9%", source: "S01" },
    { metric: "total_assets", value: 507.8e9, display: "R$ 507,8 bilhões", source: "S01" },
  ]},
  { entity_id: "BCP", perimeter: "OPERATING_BANK", geography: "Peru", currency: "PEN", as_of: "2025-12-31", metrics: [
    { metric: "total_assets", value: 204.9e9, display: "S/ 204,9 mil millones", yoy: "+3,8%", source: "S13" },
    { metric: "roae", value: 24.7, display: "24,7%", source: "S13", note: "impulsado por caída del costo de riesgo 2,13%→1,28%" },
    { metric: "cost_of_risk", value: 1.28, display: "1,28%", yoy: "from 2,13%", source: "S13" },
  ]},
  { entity_id: "CREDICORP", perimeter: "CONSOLIDATED_GROUP", geography: "Peru", currency: "PEN", as_of: "2025-12-31", metrics: [
    { metric: "total_assets", value: 267.4e9, display: "S/ 267,4 mil millones", source: "S11" },
    { metric: "net_income_attributable", value: 6.9254e9, display: "S/ 6.925,4 millones", yoy: "+25,9%", source: "S11" },
    { metric: "roae", value: 19.0, display: "19,0%", source: "S11" },
    { metric: "bcp_share_of_group_assets", value: 75.6, display: "75,6%", source: "S11" },
  ]},
];

export const TECH_CAPABILITIES: TechnologyCapability[] = [
  { tech_id: "GENAI_PLATFORM", name: "Bridge — GenAI platform", category: "GenAI", maturity: "PRODUCTION", maturity_evidence: "CTO interview feb-2026: 500+ use cases in production, 70 at scale", source_ids: ["S04"], confidence: 0.7, evidence_status: "STRONGLY_SUPPORTED", notes: "Centralized GenAI with guardrails; multi-agent, real-time voice. Pending independent corroboration." },
  { tech_id: "CONVERSATIONAL_AI", name: "BIA — virtual assistant", category: "Conversational AI", maturity: "PRODUCTION_SCALING", maturity_evidence: "24M+ users; 90% retention 4T25; 100% GenAI integrated", source_ids: ["S03","S05"], confidence: 0.85, evidence_status: "STRONGLY_SUPPORTED", notes: "Started on IBM Watson 2016; evolved to GenAI." },
  { tech_id: "MULTICLOUD", name: "Multi-cloud architecture", category: "Cloud", maturity: "SCALING", maturity_evidence: "35% workloads cloud (Feb-2024); cloud-first for new systems", source_ids: ["S06","S07"], confidence: 0.75, evidence_status: "STRONGLY_SUPPORTED", notes: "Next=Azure, Digio=AWS, Seguros=Oracle, parent=mixed. No 100% cloud target date." },
  { tech_id: "AGENTIC_AI", name: "Multi-agent architectures", category: "Agentic AI", maturity: "EXPERIMENT_PILOT", maturity_evidence: "CTO mentioned reusable multi-agent services within Bridge", source_ids: ["S04"], confidence: 0.5, evidence_status: "PARTIAL", notes: "Referenced but no specific production scale disclosed." },
  { tech_id: "DATA_VIRTUALIZATION", name: "QueryGrid data virtualization (Teradata↔Azure)", category: "Data architecture", maturity: "PRODUCTION", maturity_evidence: "Vendor case study: 400+ TB, 190,000 tables migrated", source_ids: ["S07"], confidence: 0.65, evidence_status: "STRONGLY_SUPPORTED", notes: "Vendor case study — promotional bias." },
  { tech_id: "AI_OBSERVABILITY", name: "AI observability / guardrails", category: "AI governance", maturity: "PRODUCTION", maturity_evidence: "Bridge described with centralized guardrails of responsible AI", source_ids: ["S04"], confidence: 0.6, evidence_status: "PARTIAL", notes: "Mentioned in executive interview; no technical detail." },
  { tech_id: "BIOMETRICS", name: "Biometric authentication", category: "Digital identity", maturity: "PRODUCTION", maturity_evidence: "Standard in Brazilian banking; facial biometrics per BACEN Open Finance", source_ids: ["S01"], confidence: 0.7, evidence_status: "INFERRED", notes: "Inferred from regulatory context; no Bradesco-specific deep-dive." },
  { tech_id: "OPEN_FINANCE", name: "Open Finance Brasil compliance", category: "Open Finance", maturity: "MATURE", maturity_evidence: "Mandatory BACEN framework; Bradesco is participating institution", source_ids: ["S01"], confidence: 0.85, evidence_status: "VERIFIED", notes: "Brazil mandatory since 2021. Peru's framework is less mature." },
  { tech_id: "PIX", name: "Pix integration", category: "Payments", maturity: "MATURE", maturity_evidence: "Pix is national instant-payment system; all major Brazilian banks integrated", source_ids: ["S01"], confidence: 0.9, evidence_status: "VERIFIED", notes: "Brazil's Pix (2020) is more mature than Peru's equivalent." },
  { tech_id: "GNN", name: "Graph Neural Networks (fraud)", category: "Fraud / AML", maturity: "UNKNOWN", maturity_evidence: "No public Bradesco-specific evidence found", source_ids: [], confidence: 0.2, evidence_status: "UNRESOLVED", notes: "PendingRecord." },
  { tech_id: "SYNTHETIC_DATA", name: "Synthetic data for model training", category: "Data / Model risk", maturity: "UNKNOWN", maturity_evidence: "No public Bradesco-specific evidence found", source_ids: [], confidence: 0.2, evidence_status: "UNRESOLVED", notes: "PendingRecord." },
  { tech_id: "QUANTUM_QKD", name: "Quantum-safe encryption / QKD", category: "Emerging", maturity: "EXPERIMENT_PILOT", maturity_evidence: "IBM Research: Bradesco piloted privacy-preserving encryption quantum computers cannot break, with real financial data (2024)", source_ids: ["S21"], confidence: 0.82, evidence_status: "STRONGLY_SUPPORTED", notes: "Upgrade from UNKNOWN. IBM Research (Tier A) confirma piloto con datos financieros reales. Pendiente: confirmar si escaló a producción." },
  { tech_id: "DLT_TOKENIZATION", name: "DLT / tokenization / stablecoin", category: "Emerging", maturity: "PILOT", maturity_evidence: "Parfin-Bradesco stablecoin cross-border pilot (ene-2025); R$10B capital increase for blockchain/stablecoin/digital asset custody (jul-2026); 'no turning back' executive quote", source_ids: ["S22","S23","S24"], confidence: 0.85, evidence_status: "INDEPENDENTLY_CORROBORATED", notes: "Upgrade from UNKNOWN. 3 independent clusters corroboran. Escalando hacia custodia de activos digitales." },
];

export const INITIATIVES: InitiativeRecord[] = [
  { initiative_id: "NEXT", name: "Next (banco digital)", category: "Digital bank", lifecycle: "INTEGRATED", first_seen: "2017-06", last_seen: "2026-06", original_promise: "Primer banco 100% digital de Bradesco dirigido a público joven; operación separada y ágil", later_outcome: "Reincorporado al banco matriz como segmento de atención (fines 2023-2024). App sigue activo (Google Play jun-2026).", interpretation: "INTEGRATED ≠ FAILED. Decisión consciente de consolidar tras madurez digital del banco matriz.", evidence_status: "INDEPENDENTLY_CORROBORATED", source_ids: ["S03","S10"] },
  { initiative_id: "BITZ", name: "Bitz (cartera digital)", category: "Digital wallet", lifecycle: "SUNSET", first_seen: "2020", last_seen: "2023", original_promise: "Cartera digital de pagos para captar clientes no bancarizados", later_outcome: "Cerrada en 2023; clientes migrados a Digio", interpretation: "SUNSET confirmado. Consolidación hacia Digio.", evidence_status: "INDEPENDENTLY_CORROBORATED", source_ids: ["S03","S06"] },
  { initiative_id: "DIGIO", name: "Digio (banco digital subsidiario)", category: "Digital bank", lifecycle: "PRODUCTION", first_seen: "2021 (adquisición)", last_seen: "2026", original_promise: "Banco digital low-cost; infraestructura propia AWS", later_outcome: "100% controlado; AWS separada de Next (Azure); management declara mantenerlo independiente", interpretation: "PRODUCTION. Estrategia dual-cloud deliberada.", evidence_status: "INDEPENDENTLY_CORROBORATED", source_ids: ["S06","S01"] },
  { initiative_id: "BIA", name: "BIA (asistente virtual)", category: "Conversational AI", lifecycle: "PRODUCTION_SCALING", first_seen: "2016", last_seen: "2026", original_promise: "Asistente virtual basado en IBM Watson para atender clientes en app", later_outcome: "Evolucionó a 100% GenAI; 24M+ usuarios; 90% retención 4T25", interpretation: "SUCCESS — evolución tecnológica sostenida por 10 años.", evidence_status: "STRONGLY_SUPPORTED", source_ids: ["S03","S05"] },
  { initiative_id: "BRIDGE", name: "Bridge (plataforma GenAI)", category: "GenAI platform", lifecycle: "PRODUCTION", first_seen: "2024 (approx.)", last_seen: "2026-02", original_promise: "Centralizar IA generativa corporativa con guardrails responsables", later_outcome: "500+ casos de uso en producción, 70 a escala (según CTO feb-2026)", interpretation: "PRODUCTION, pero cifra auto-reportada requiere corroboración independiente.", evidence_status: "STRONGLY_SUPPORTED", source_ids: ["S04"] },
  { initiative_id: "INOVABRA", name: "Inovabra habitat", category: "Innovation lab", lifecycle: "MATURE_PRODUCTION", first_seen: "2018-02", last_seen: "2026", original_promise: "Espacio físico de co-innovación con startups y corporaciones", later_outcome: "Crecimiento: 190 startups (2019) → 230 startups, 80 empresas, 8 hubs (2026)", interpretation: "MATURE como programa. ROI agregado no cuantificado públicamente.", evidence_status: "VERIFIED", source_ids: ["S08","S09"] },
  { initiative_id: "SEG_DIGITAL", name: "Bradesco Seguros digital", category: "Insurance digital", lifecycle: "PRODUCTION", first_seen: "pre-2020", last_seen: "2026", original_promise: "Digitalización de seguros sobre Oracle cloud", later_outcome: "ROAE 21,9% en 2025 — más rentable que el brazo bancario", interpretation: "SUCCESS — el brazo de seguros supera al bancario en rentabilidad.", evidence_status: "VERIFIED", source_ids: ["S01","S06"] },
  { initiative_id: "TERADATA_MIGRATION", name: "Migración analítica Teradata → Azure", category: "Data architecture", lifecycle: "PRODUCTION", first_seen: "2024 (approx.)", last_seen: "2025-07", original_promise: "Migración híbrida del entorno analítico a Azure con QueryGrid", later_outcome: "400+ TB, 190.000 tablas migradas (caso Teradata jul-2025)", interpretation: "PRODUCTION, pero evidencia de vendor case study (sesgo).", evidence_status: "STRONGLY_SUPPORTED", source_ids: ["S07"] },
];

export const SEGMENTS: BankSegment[] = [
  { name: "Banca minorista (retail)", bradesco: "Núcleo del banco; 19M→28M clientes digitales (1T26)", bcp: "Banca masiva; Yape como puerta de entrada digital", note: "Bradesco tiene ~11× más activos absolutos; comparar market share doméstico, no absolutos" },
  { name: "Affluent / Prime", bradesco: "Bradesco Prime (segmento de atención diferenciada)", bcp: "BCP Prime / BCP Premium", note: "Estructura de segmentos comparable" },
  { name: "Private banking", bradesco: "Bradesco Private (a través de Ágora para corretaje)", bcp: "BCP Wealth / Credicorp Capital", note: "Bradesco adquirió Ágora (2008); Credicorp tiene Credicorp Capital" },
  { name: "PYME / SME", bradesco: "Bradesco Empresas; productos integrados de crédito + servicios", bcp: "BCP Pyme; BCP Xplore APIs para recaudación", note: "Ambos con enfoque de ecosistema" },
  { name: "Corporate", bradesco: "Bradesco BBI (banca de inversión); Bradescard (tarjetas co-branded)", bcp: "BCP Corporate; Credicorp Capital", note: "Bradesco BBI es banca de inversión dedicada" },
  { name: "Digital-native", bradesco: "Next (segmento de marca); Digio (subsidiaria AWS)", bcp: "Yape (app de pagos dentro de BCP); Tenpo (Chile)", note: "Next = brand-within-bank; Yape = payment-app-within-BCP. Estructuras distintas" },
  { name: "Microfinanzas", bradesco: "No es foco histórico de Bradesco", bcp: "Mibanco (subsidiaria de Credicorp, líder en microfinanzas Perú)", note: "Mibanco es ventaja estructural de Credicorp en este segmento" },
  { name: "Seguros", bradesco: "Bradesco Seguros (ROAE 21,9%; mayor que bancario)", bcp: "Grupo Pacífico (seguros, dentro de Credicorp)", note: "Ambos grupos son multi-negocio banca+seguros" },
];

export const CHANNELS: ChannelMap[] = [
  { channel: "Sucursales físicas", bradesco: "Red histórica en Brasil (en reducción gradual, alineada con estrategia digital)", bcp: "Red principal en Perú; BCP es el banco con mayor footprint físico del país" },
  { channel: "App móvil", bradesco: "App Bradesco + BIA integrado (24M+ usuarios)", bcp: "App BCP + Yape integrado; BCP Xplore para APIs" },
  { channel: "Asistente virtual", bradesco: "BIA (90% retención 4T25; 100% GenAI)", bcp: "Asistente BCP (no se encontró métrica pública equivalente de retención — OPEN_QUESTION)" },
  { channel: "WhatsApp", bradesco: "BIA disponible en WhatsApp", bcp: "BCP disponible en WhatsApp (canal de atención)" },
  { channel: "Web / internet banking", bradesco: "Portal Bradesco + Next (digital-first)", bcp: "Portal BCP + BCP Xplore" },
  { channel: "ATMs / cajeros", bradesco: "Red Brasil (biometría facial)", bcp: "Red BCP Perú (biometría)" },
  { channel: "Corresponsales no bancarios", bradesco: "Correspondentes bancários (amplia red Brasil)", bcp: "Agentes BCP (red de agentes en Perú)" },
  { channel: "Open Finance / APIs", bradesco: "Participante Open Finance Brasil (obligatorio)", bcp: "BCP Xplore (Open Banking APIs propias)" },
  { channel: "Pagos instantáneos", bradesco: "Pix (sistema nacional Brasil, maduro)", bcp: "Yape (app de pagos; equivalenten menos maduro a nivel de infraestructura nacional obligatoria)" },
];

export const PRODUCTS: ProductEcosystemNode[] = [
  { name: "Cuenta corriente", category: "Depósitos", bradesco: "Cuenta Bradesco + Next (digital)", bcp: "Cuenta BCP + BCP Xplore" },
  { name: "Cuenta de ahorros", category: "Depósitos", bradesco: "Poupança Bradesco (tradicional + digital)", bcp: "Ahorro BCP" },
  { name: "CDB / depósito a plazo", category: "Depósitos", bradesco: "R$727,9B depósitos totales", bcp: "Depósitos a plazo BCP" },
  { name: "Crédito personal", category: "Crédito", bradesco: "Bradesco Financiamentos", bcp: "Préstamos BCP" },
  { name: "Crédito vehicular", category: "Crédito", bradesco: "Bradesco Financiamentos (líder histórico)", bcp: "BCP Auto" },
  { name: "Tarjetas de crédito", category: "Tarjetas", bradesco: "Bradescard (co-branded); tarjetas Bradesco", bcp: "Tarjetas BCP; BCP Xplore financiamiento flexible" },
  { name: "Seguros de vida", category: "Seguros", bradesco: "Bradesco Vida e Previdência (R$10,1B utilidad)", bcp: "Pacifico Vida (Grupo Pacífico)" },
  { name: "Seguros generales", category: "Seguros", bradesco: "Bradesco Seguros (auto, residencia)", bcp: "Pacifico Seguros" },
  { name: "Previdência / pensiones", category: "Pensiones", bradesco: "Bradesco Previdência", bcp: "Prima AFP (subsidiaria Credicorp)" },
  { name: "Wealth / inversión", category: "Wealth", bradesco: "Ágora Corretora (adquirida 2008)", bcp: "Credicorp Capital; BCP Wealth" },
  { name: "Microfinanzas", category: "Microfinanzas", bradesco: "No es foco histórico", bcp: "Mibanco (líder Perú)" },
  { name: "Pagos instantáneos", category: "Pagos", bradesco: "Pix integrado", bcp: "Yape (app de pagos)" },
  { name: "Adquisición / acquiring", category: "Pagos", bradesco: "Cielo (Bradesco fue socio fundador histórico)", bcp: "Culqi (adquirida por Credicorp); Nequi" },
  { name: "Banca de inversión", category: "Corporate", bradesco: "Bradesco BBI", bcp: "Credicorp Capital" },
];

export const PLATFORMS: PlatformRecord[] = [
  { name: "App Bradesco + BIA", type: "Mobile banking + AI assistant", owner: "BRADESCO_BANK", status: "PRODUCTION_SCALING", cloud: "Azure + mixed", note: "BIA 24M+ usuarios; 90% retención; 100% GenAI" },
  { name: "Next", type: "Digital bank brand", owner: "BRADESCO_BANK", status: "INTEGRATED", cloud: "Azure", note: "Reincorporado como segmento; app activo jun-2026" },
  { name: "Digio", type: "Digital bank subsidiary", owner: "BRADESCO_BANK", status: "PRODUCTION", cloud: "AWS", note: "100% controlado; infraestructura separada deliberadamente" },
  { name: "Bridge", type: "GenAI platform", owner: "BRADESCO_BANK", status: "PRODUCTION", cloud: "Multi", note: "500+ use cases; 70 at scale; guardrails centralizados" },
  { name: "Bradesco Seguros platform", type: "Insurance platform", owner: "BRADESCO_SEGUROS", status: "PRODUCTION", cloud: "Oracle", note: "ROAE 21,9%" },
  { name: "Inovabra habitat", type: "Innovation space + network", owner: "ORG_BRADESCO", status: "MATURE_PRODUCTION", cloud: "N/A (physical)", note: "230 startups, 80 empresas, 8 hubs" },
  { name: "BCP App + Yape", type: "Mobile banking + payments", owner: "BCP", status: "PRODUCTION_SCALING", cloud: "BCP infrastructure", note: "Yape meta 16,5M usuarios 2026" },
  { name: "BCP Xplore", type: "Open Banking / APIs", owner: "BCP", status: "PRODUCTION", cloud: "BCP infrastructure", note: "Recaudación, pagos automáticos, financiamiento flexible" },
  { name: "Krealo", type: "Corporate venture fund", owner: "CREDICORP", status: "PRODUCTION", cloud: "N/A", note: "Hands-on VC model" },
];

export const RADAR_VERSIONS: RadarVersion[] = [
  { version_id: "RADAR_2022", organization: "Banco Bradesco", publication_date: "2022-06-01", evidence_date: "2022-06-01", source: "Reconstructed from IR + press (no formal published radar)", technology_items: [
    { name: "Watson-based BIA", maturity: "PRODUCTION", category: "Conversational AI" },
    { name: "Cloud migration (early)", maturity: "EXPERIMENT_PILOT", category: "Cloud" },
    { name: "Biometrics (facial)", maturity: "PRODUCTION", category: "Digital identity" },
    { name: "Open Finance readiness", maturity: "PILOT", category: "Open Finance" },
  ]},
  { version_id: "RADAR_2024", organization: "Banco Bradesco", publication_date: "2024-02-20", evidence_date: "2024-02-20", source: "Multicloud announcement + IR", technology_items: [
    { name: "BIA (Watson + GenAI transition)", maturity: "PRODUCTION", category: "Conversational AI", changed_from: "RADAR_2022: Watson-primary → GenAI-integrated" },
    { name: "Multicloud (Azure/AWS/Oracle)", maturity: "SCALING", category: "Cloud", changed_from: "RADAR_2022: EXPERIMENT_PILOT → SCALING (35%)" },
    { name: "Open Finance compliance", maturity: "MATURE", category: "Open Finance", changed_from: "RADAR_2022: PILOT → MATURE (mandatory)" },
    { name: "Pix integration", maturity: "MATURE", category: "Payments", first_seen: true },
    { name: "GenAI pilots (pre-Bridge)", maturity: "EXPERIMENT", category: "GenAI", first_seen: true },
  ]},
  { version_id: "RADAR_2026", organization: "Banco Bradesco", publication_date: "2026-02-10", evidence_date: "2026-02-10", source: "CTO interview + 4T25 earnings call", technology_items: [
    { name: "BIA (100% GenAI)", maturity: "PRODUCTION_SCALING", category: "Conversational AI", changed_from: "RADAR_2024: PRODUCTION → PRODUCTION_SCALING (90% retention)" },
    { name: "Bridge (GenAI platform)", maturity: "PRODUCTION", category: "GenAI", changed_from: "RADAR_2024: EXPERIMENT → PRODUCTION (500+ use cases)", note: "Bridge named explicitly" },
    { name: "Multicloud (hybrid)", maturity: "SCALING", category: "Cloud" },
    { name: "Multi-agent architectures", maturity: "EXPERIMENT_PILOT", category: "Agentic AI", first_seen: true, note: "Referenced within Bridge; no scale disclosed" },
    { name: "Data virtualization (QueryGrid)", maturity: "PRODUCTION", category: "Data architecture", first_seen: true },
    { name: "AI observability/guardrails", maturity: "PRODUCTION", category: "AI governance", first_seen: true },
    { name: "Quantum-safe encryption", maturity: "EXPERIMENT_PILOT", category: "Emerging", changed_from: "RADAR_2026: UNKNOWN → EXPERIMENT_PILOT (IBM Research pilot)", note: "Upgrade from PendingRecord" },
    { name: "DLT / stablecoin / tokenization", maturity: "PILOT", category: "Emerging", changed_from: "RADAR_2026: UNKNOWN → PILOT (Parfin partnership + R$10B capital increase)", note: "Upgrade from PendingRecord" },
    { name: "GNN (fraud)", maturity: "UNKNOWN", category: "Fraud/AML", note: "Not on radar — PendingRecord (no Bradesco-specific evidence)" },
    { name: "Synthetic data", maturity: "UNKNOWN", category: "Data/Model risk", note: "Not on radar — PendingRecord" },
  ]},
];

export const RECOMMENDATIONS: RecommendationRecord[] = [
  { rec_id: "REC01", title: "Centralizar una plataforma de IA generativa con gobernanza única (patrón tipo Bridge)", audience: "Líderes de emerging-technology / new-products en BCP Perú", transferability: "REASONABLE_TO_TRANSFER", supporting_claim_ids: ["C006","C005","C007"], contradicting_claim_ids: [], assumptions: ["La lógica de una capa horizontal de servicios de IA con guardrails centralizados no depende del tamaño del banco, aunque el volumen de casos de uso sí escala con los recursos."], confidence: 0.7, what_would_change_my_mind: "Evidencia de que BCP ya tiene una capa equivalente centralizada y publicada, o de que el modelo distribuido por unidad de negocio produce mejores resultados en bancos del tamaño de BCP.", action: "Diseñar/auditar una capa horizontal de GenAI con guardrails de cumplimiento centralizados, reutilizable por todas las unidades de negocio, con métricas de adopción internas." },
  { rec_id: "REC02", title: "Evaluar la consolidación de marcas digitales fragmentadas cuando el banco matriz alcanza madurez digital propia", audience: "Líderes de estrategia digital en Credicorp/BCP", transferability: "CONDITIONAL", supporting_claim_ids: ["C010","C011","C012"], contradicting_claim_ids: [], assumptions: ["La fragmentación de marcas digitales puede generar costos de coordinación que superan sus beneficios de posicionamiento una vez que el banco matriz alcanza cierto nivel de madurez digital propia."], confidence: 0.6, what_would_change_my_mind: "Evidencia de que Yape/Tenpo/Culqi generan valor marginal superior bajo operación independiente que bajo consolidación.", action: "Realizar un análisis de costos de coordinación vs beneficios de segmentación de las marcas digitales del grupo cada 18-24 meses." },
  { rec_id: "REC03", title: "No adoptar el modelo 'habitat' físico de Inovabra sin evaluar el modelo de cartera de venture interno ya existente en Credicorp", audience: "Líderes de innovación en Credicorp/BCP", transferability: "NOT_EVIDENCE_BASED", supporting_claim_ids: ["C009","C015"], contradicting_claim_ids: [], assumptions: ["No hay evidencia comparativa de retorno que permita recomendar la transferencia de un modelo sobre el otro sin más investigación."], confidence: 0.5, what_would_change_my_mind: "Un benchmark cuantitativo de ROI entre modelos de habitat abierto vs cartera de venture interno, controlado por escala de mercado.", action: "Documentar el ROI del modelo actual (cartera Yape/Tenpo/Krealo) antes de considerar replicar el modelo habitat." },
  { rec_id: "REC04", title: "No usar cifras específicas de Bradesco como benchmarks objetivos para BCP sin ajuste", audience: "Equipos de emerging-technology y new-products en Perú", transferability: "DO_NOT_TRANSFER", supporting_claim_ids: ["C005","C006","C017"], contradicting_claim_ids: [], assumptions: ["Las cifras de Bradesco (90% retención BIA, 500 casos Bridge, 40x reducción de costo) son auto-reportadas y dependen de definiciones internas y de escala de mercado."], confidence: 0.8, what_would_change_my_mind: "Normalización explícita de definiciones entre Bradesco y BCP, con auditoría externa.", action: "Antes de citar cualquier cifra de Bradesco como benchmark, exigir reconciliación de definición de métrica y ajuste por escala." },
  { rec_id: "REC05", title: "Aprovechar la madurez regulatoria brasileña (Open Finance obligatorio, Pix) como horizonte de preparación para Perú", audience: "Líderes regulatorios y de tecnología en BCP", transferability: "REASONABLE_TO_LEARN_FROM", supporting_claim_ids: [], contradicting_claim_ids: [], assumptions: ["Perú avanzará (a su ritmo) hacia marcos de Open Finance e instant payments más maduros."], confidence: 0.65, what_would_change_my_mind: "Evidencia de que el marco peruano seguirá un camino estructuralmente distinto.", action: "Mapear las capacidades que Bradesco tuvo que construir para Open Finance Brasil/Pix y anticipar las equivalentes para BCP." },
];

export const OPEN_QUESTIONS: OpenQuestionRecord[] = [
  { oq_id: "OQ01", question: "¿Cuántos casos de uso de IA en producción tiene BCP/Credicorp, comparable a los '500 casos de uso' de Bradesco Bridge?", context: "ACTUALIZADO (ago-2026): BCP tiene IA en producción (Forbes Perú: pionero en IA generativa para software; GenIA tool; IA marketing performance). Pero no hay conteo granular comparable a los 500 de Bradesco. La comparación sigue siendo asimétrica.", what_would_resolve: "Una métrica cuantitativa de Credicorp/BCP sobre número de casos de uso de IA en producción, o una decisión explícita de no comparar granularidad.", priority: "MEDIUM" },
  { oq_id: "OQ02", question: "¿Cuál es el retorno económico agregado de Inovabra habitat?", context: "RESUELTO PARCIALMENTE (ago-2026): Inovabra Ventures = R$400M fondo (40% de inversiones PE del banco); startups +55% faturamento (2019); 500 contratos firmados (2021). ROI cuantificable pero histórico.", what_would_resolve: "Métrica de ROI agregada actualizada (post-2022) de Bradesco sobre Inovabra.", priority: "LOW" },
  { oq_id: "OQ03", question: "¿Cuál es el verdadero estado de madurez de Bridge (los 500 casos de uso)?", context: "RESUELTO (ago-2026): Bridge ahora corroborado independientemente por Forbes Brasil (Tier C), Red Hat (vendor), Funds Society (Tier C). Upgrade a INDEPENDENTLY_CORROBORATED.", what_would_resolve: "Resuelto. Para mayor confianza: auditoría externa o métricas operativas (cost-to-serve, NPS) vinculadas a Bridge.", priority: "LOW" },
  { oq_id: "OQ04", question: "Normalización de tamaño ajustada por PIB/población bancarizada entre Brasil y Perú", context: "La comparación de tamaño absoluto (R$2,33T vs S/204,9B) es NOT_DIRECTLY_COMPARABLE sin normalización.", what_would_resolve: "Cálculo de market share doméstico o ratio activos/PIB para cada banco.", priority: "MEDIUM" },
  { oq_id: "OQ05", question: "¿Existe un 'Technology Radar' formal o un método BTRL de readiness en Bradesco?", context: "No se encontró evidencia pública de un radar formal publicado por Bradesco en esta ronda.", what_would_resolve: "Documentación oficial de Bradesco sobre su método de evaluación de madurez tecnológica.", priority: "MEDIUM" },
  { oq_id: "OQ06", question: "Estado actual de CIX-BCP (proyecto de innovación 2018 en GitHub)", context: "Evidencia histórica sugiere plataforma interna. No hay evidencia reciente de actividad.", what_would_resolve: "Confirmación oficial de BCP/Credicorp sobre el estado actual del proyecto CIX.", priority: "LOW" },
  { oq_id: "OQ07", question: "Bradesco: deep-dive en digital identity, biometría, GNN, datos sintéticos, quantum/QKD, DLT/tokenization, stablecoins", context: "PARCIALMENTE RESUELTO (ago-2026): Quantum-safe encryption = EXPERIMENT_PILOT (IBM Research); DLT/stablecoin = PILOT (Parfin + R$10B capital increase). Pendientes: GNN, datos sintéticos, biometría deep-dive.", what_would_resolve: "Ciclos adicionales para GNN, datos sintéticos, y deep-dive de biometría.", priority: "LOW" },
  { oq_id: "OQ08", question: "¿La diferencia observada en volumen de iniciativas de IA (Bradesco > BCP) refleja madurez real o diferencia de comunicación corporativa?", context: "Hipótesis H1-H4 activas. No hay evidencia que discrimine concluyentemente.", what_would_resolve: "Métricas comparables de outcome (e.g., cost-to-serve, NPS digital, conversion) entre ambos bancos.", priority: "HIGH" },
];

export const CONTRADICTIONS: ContradictionRecord[] = [
  { ct_id: "CT01", claim_ids: ["C005"], type: "DEFINITIONAL_DRIFT", description: "La cifra de retención de BIA pasó de '85-90%' (jun-2025) a '90%' (4T25). No está claro si la definición de 'retención' es idéntica entre ambas fechas.", status: "UNRESOLVED", resolution_note: "Asumir 85-90% como rango y 90% como punto más reciente. No afecta la clasificación PRODUCTION_SCALING." },
  { ct_id: "CT02", claim_ids: ["C006"], type: "SINGLE_SOURCE", description: "La cifra de '500 casos de uso en producción' para Bridge proviene de una única entrevista con la CTO (feb-2026). No hay corroboración independiente Tier C.", status: "RESOLVED_BY_LABELING", resolution_note: "RESUELTO (ago-2026): Bridge ahora corroborado por 3 clusters independientes (Forbes Brasil Tier C, Red Hat vendor, Funds Society Tier C). Claim C006 upgraded a INDEPENDENTLY_CORROBORATED. CT02 cerrado." },
  { ct_id: "CT03", claim_ids: ["C008"], type: "TEMPORAL_STALENESS", description: "La cifra de '35% workloads in cloud' es de feb-2024. Es probable que haya aumentado para 2026, pero no hay cifra actualizada públicamente.", status: "PARTIALLY_RESOLVED", resolution_note: "Tratada como historical baseline; la estrategia cloud-first sigue vigente, pero el % exacto es stale." },
  { ct_id: "CT04", claim_ids: ["C013","C002"], type: "COMPARABILITY_TENSION", description: "ROAE Bradesco 15.2% vs BCP 24.7%. Ambas son ROAE pero la base de capital, la estructura de ingresos y el ciclo de crédito difieren entre Brasil y Perú.", status: "RESOLVED_BY_LABELING", resolution_note: "Etiquetado COMPARABLE (dimensión), pero con nota: la diferencia puede reflejar ciclo de crédito y estructura de mercado, no solo capacidad operativa." },
];

export const ROADMAP = [
  { year: "2026", item: "Inversión en tecnología +16% (proyectado vs 2025)", owner: "BRADESCO", status: "IN_PROGRESS", source: "S04" },
  { year: "2026", item: "10.500 profesionales de tecnología (~6.500 internos)", owner: "BRADESCO", status: "ACHIEVED", source: "S04" },
  { year: "2026", item: "Yape: 16,5M usuarios + S/600B transacciones (meta)", owner: "CREDICORP", status: "TARGET", source: "S12" },
  { year: "2026", item: "Iniciativas disruptivas = 10% de ingresos ajustados por riesgo del grupo", owner: "CREDICORP", status: "TARGET", source: "S12" },
  { year: "2028", item: "Índice de eficiencia Bradesco = 40% (meta desde 50% en 2025)", owner: "BRADESCO", status: "TARGET", source: "S03" },
];

export const EXTERNAL_SIGNALS = [
  { signal: "App Bradesco en Google Play", type: "CUSTOMER_SIGNAL", tier: "D", content: "App activa y actualizada (jun-2026). Calificaciones y volumen de reseñas sugieren base de usuarios amplia.", entity: "BRADESCO_BANK", source: "Google Play (Tier D signal)" },
  { signal: "App Next en Google Play", type: "CUSTOMER_SIGNAL", tier: "D", content: "App aún activa y actualizada tras reincorporación (jun-2026). Confirma INTEGRATED (no sunset).", entity: "NEXT", source: "S10" },
  { signal: "Reclame Aqui (Brasil)", type: "CUSTOMER_SIGNAL", tier: "D", content: "Plataforma de reclamos brasileña; presencia de Bradesco es esperada para un banco de su escala. Sin análisis cuantitativo en esta ronda.", entity: "BRADESCO_BANK", source: "Reclame Aqui (Tier D signal)" },
  { signal: "LinkedIn empleos Bradesco", type: "TALENT_SIGNAL", tier: "D", content: "Job postings consistentes con inversión en tecnología (+35% desarrolladores desde 2024). Refuerza C007.", entity: "BRADESCO_BANK", source: "LinkedIn (Tier D signal)" },
  { signal: "Yape adopción Perú", type: "CUSTOMER_SIGNAL", tier: "C", content: "Yape alcanzó rentabilidad antes de lo proyectado; meta 16,5M usuarios activos para 2026.", entity: "YAPE", source: "S12 (Tier A/B)" },
  { signal: "CIX-BCP GitHub (2018)", type: "UNVERIFIED", tier: "D", content: "Proyecto histórico de innovación; sin evidencia reciente de actividad. Status UNKNOWN.", entity: "BCP", source: "S16 (AMBIGUOUS)" },
];

export const PARTNERSHIPS = [
  { partner: "IBM", type: "TECH_VENDOR", scope: "Watson (BIA legacy engine 2016-); evolución a GenAI", status: "EVOLVED", evidence: "S05", perimeter: "BRADESCO_BANK" },
  { partner: "Microsoft Azure", type: "CLOUD_PROVIDER", scope: "Next cloud; analytics migration target", status: "ACTIVE", evidence: "S06,S07", perimeter: "BRADESCO_BANK" },
  { partner: "Amazon Web Services", type: "CLOUD_PROVIDER", scope: "Digio and (former) Bitz cloud", status: "ACTIVE", evidence: "S06", perimeter: "DIGIO" },
  { partner: "Oracle", type: "CLOUD_PROVIDER", scope: "Bradesco Seguros cloud", status: "ACTIVE", evidence: "S06", perimeter: "BRADESCO_SEGUROS" },
  { partner: "Teradata", type: "DATA_VENDOR", scope: "Hybrid analytical environment; QueryGrid", status: "ACTIVE", evidence: "S07", perimeter: "BRADESCO_BANK", bias_note: "Vendor case study — promotional" },
  { partner: "WeWork", type: "OPERATING_PARTNER", scope: "Inovabra habitat physical space", status: "ACTIVE_SINCE_2018", evidence: "S08,S09", perimeter: "INOVABRA" },
  { partner: "Banco do Brasil (former)", type: "JV_DIVESTED", scope: "Former 49,99% JV partner in Digio; bought out 2021-2022 for R$625M", status: "DIVESTED", evidence: "S06", perimeter: "DIGIO" },
  { partner: "Startups (Inovabra network)", type: "OPEN_INNOVATION", scope: "230 startups in habitat (2026)", status: "ACTIVE", evidence: "S08", perimeter: "INOVABRA" },
  { partner: "Universities", type: "RESEARCH", scope: "Not researched in depth in this round", status: "UNKNOWN", evidence: [], perimeter: "ORG_BRADESCO", note: "PendingRecord" },
  { partner: "Krealo portfolio startups", type: "CORPORATE_VENTURE", scope: "Krealo fund investments", status: "ACTIVE", evidence: "S14", perimeter: "CREDICORP" },
  { partner: "Culqi", type: "ACQUIRED", scope: "Payment gateway", status: "INTEGRATED", evidence: "S12", perimeter: "CREDICORP" },
  { partner: "Open Banking ecosystem (Peru)", type: "STANDARDS", scope: "BCP Xplore APIs", status: "ACTIVE", evidence: "S15", perimeter: "BCP" },
];

export const HYPOTHESES = [
  { hypothesis_id: "H1", observation: "Bradesco comunica públicamente un volumen mayor de iniciativas de IA/tecnología que Credicorp para BCP.", hypothesis: "Bradesco tiene mayor madurez real (H1 — madurez real superior)", explanation: "El banco efectivamente ha centralizado y escalado más casos de uso de IA en producción, apoyado por una inversión tecnológica mayor en términos absolutos.", evidence_for: ["+22% tech investment 2025","10,500 tech professionals","Bridge centralized platform claim"], evidence_against: ["500 use cases is single-source","no audited definition of 'use case'"], status: "PLAUSIBLE_NOT_CONFIRMED" },
  { hypothesis_id: "H2", observation: "Same observation.", hypothesis: "Diferencia de estilo de comunicación corporativa (H2)", explanation: "Bradesco, como emisor listado en NYSE bajo escrutinio de analistas globales, tiene incentivos más fuertes para narrar transformación cuantificada. Credicorp comunica innovación en términos de contribución a ingresos (lenguaje financiero distinto).", evidence_for: ["Credicorp IR communicates '10% of risk-adjusted revenue' — financial framing","Bradesco CTO interview style is highly metric-forward"], evidence_against: ["Does not disprove H1"], status: "PLAUSIBLE_NOT_CONFIRMED" },
  { hypothesis_id: "H3", observation: "Same observation.", hypothesis: "El tamaño permite mayor volumen de experimentación, sin mejor conversión por unidad (H3)", explanation: "Bradesco puede ejecutar más experimentos por su tamaño absoluto, pero su tasa de conversión a producción por unidad de inversión puede no ser superior.", evidence_for: ["Scale asymmetry is real (Brazil ≈10× Peru)"], evidence_against: ["No public data on conversion rates per unit of investment"], status: "PLAUSIBLE_NOT_CONFIRMED" },
  { hypothesis_id: "H4", observation: "Same observation.", hypothesis: "Diferencias regulatorias y de infraestructura explican la brecha (H4)", explanation: "Brasil tiene Open Finance y Pix más maduros y de adopción obligatoria más temprana que el marco peruano, generando más casos de uso digital observables independientemente de la capacidad interna relativa.", evidence_for: ["Brazil Open Finance mandatory since 2021","Pix is national instant-payment (2020)","Peru's framework less mature"], evidence_against: ["Does not explain BIA/Bridge GenAI claims (not directly Open Finance dependent)"], status: "PARTIALLY_SUPPORTED" },
];

export const KPIS = [
  { metric: "ROAE Bradesco", value: "15,2%", target: "Sostener > costo de capital", period: "4T25", source: "S02" },
  { metric: "Índice de eficiencia Bradesco", value: "50%", target: "40% en 2028", period: "2025", source: "S03" },
  { metric: "Retención BIA", value: "90%", target: "Sostener / mejorar", period: "4T25", source: "S03" },
  { metric: "Casos de uso Bridge en producción", value: "500+ (70 a escala)", target: "n/a (auto-reportado)", period: "feb-2026", source: "S04" },
  { metric: "Clientes digitales Bradesco", value: "28M", target: "Crecimiento sostenido", period: "1T26", source: "S03" },
  { metric: "ROAE BCP", value: "24,7%", target: "Sostener", period: "2025", source: "S13" },
  { metric: "Costo de riesgo BCP", value: "1,28%", target: "Mantener bajo", period: "2025", source: "S13" },
  { metric: "Usuarios Yape (meta)", value: "16,5M", target: "2026", period: "meta 2026", source: "S12" },
  { metric: "Transacciones Yape (meta)", value: "S/600B", target: "2026", period: "meta 2026", source: "S12" },
];

export function getSource(id: string): SourceRecord | undefined {
  return SOURCES.find((s) => s.source_id === id);
}
export function getClaimsForSection(sectionId: string): ClaimRecord[] {
  return CLAIMS.filter((c) => c.report_sections?.includes(sectionId));
}
